"""Add point-in-time market data catalog

Revision ID: 0004_point_in_time_data
Revises: 0003_submission_attempts
Create Date: 2026-07-15 14:23:12.051718
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0004_point_in_time_data"
down_revision: str | None = "0003_submission_attempts"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "calendar_versions",
        sa.Column("calendar_version", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("tzdata_version", sa.String(length=32), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "length(content_hash) = 64",
            name=op.f("ck_calendar_versions_calendar_versions_hash_length"),
        ),
        sa.PrimaryKeyConstraint("calendar_version", name=op.f("pk_calendar_versions")),
        sa.UniqueConstraint("content_hash", name=op.f("uq_calendar_versions_content_hash")),
    )
    op.create_table(
        "corporate_action_sets",
        sa.Column("corporate_action_version", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "length(content_hash) = 64",
            name=op.f("ck_corporate_action_sets_corporate_action_sets_hash_length"),
        ),
        sa.PrimaryKeyConstraint("corporate_action_version", name=op.f("pk_corporate_action_sets")),
        sa.UniqueConstraint("content_hash", name=op.f("uq_corporate_action_sets_content_hash")),
    )
    op.create_table(
        "data_objects",
        sa.Column("object_id", sa.String(length=64), nullable=False),
        sa.Column("object_key", sa.String(length=256), nullable=False),
        sa.Column("byte_checksum", sa.String(length=64), nullable=False),
        sa.Column("semantic_checksum", sa.String(length=64), nullable=False),
        sa.Column("format", sa.String(length=16), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "format = 'parquet'", name=op.f("ck_data_objects_data_objects_parquet_only")
        ),
        sa.CheckConstraint(
            "length(object_id) = 64 AND length(byte_checksum) = 64 AND length(semantic_checksum) = 64",
            name=op.f("ck_data_objects_data_objects_hash_lengths"),
        ),
        sa.CheckConstraint(
            "size_bytes > 0", name=op.f("ck_data_objects_data_objects_positive_size")
        ),
        sa.PrimaryKeyConstraint("object_id", name=op.f("pk_data_objects")),
        sa.UniqueConstraint("byte_checksum", name=op.f("uq_data_objects_byte_checksum")),
        sa.UniqueConstraint("object_key", name=op.f("uq_data_objects_object_key")),
    )
    op.create_table(
        "instruments",
        sa.Column("instrument_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("asset_class", sa.String(length=24), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "asset_class IN ('etf', 'equity')",
            name=op.f("ck_instruments_instruments_valid_asset_class"),
        ),
        sa.PrimaryKeyConstraint("instrument_id", name=op.f("pk_instruments")),
    )
    op.create_table(
        "market_data_sources",
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("dataset", sa.String(length=64), nullable=False),
        sa.Column("feed", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("licensed", sa.Boolean(), nullable=False),
        sa.Column("detail", sa.String(length=512), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "kind IN ('synthetic_fixture', 'recorded_fixture', 'vendor')",
            name=op.f("ck_market_data_sources_market_data_sources_valid_kind"),
        ),
        sa.PrimaryKeyConstraint("source_id", name=op.f("pk_market_data_sources")),
    )
    op.create_table(
        "universe_versions",
        sa.Column("universe_version", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("effective_as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.CheckConstraint(
            "length(content_hash) = 64",
            name=op.f("ck_universe_versions_universe_versions_hash_length"),
        ),
        sa.PrimaryKeyConstraint("universe_version", name=op.f("pk_universe_versions")),
        sa.UniqueConstraint("content_hash", name=op.f("uq_universe_versions_content_hash")),
    )
    op.create_table(
        "calendar_sessions",
        sa.Column("calendar_version", sa.String(length=64), nullable=False),
        sa.Column("session_label", sa.String(length=10), nullable=False),
        sa.Column("opens_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("closes_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("half_day", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "closes_at > opens_at",
            name=op.f("ck_calendar_sessions_calendar_sessions_positive_duration"),
        ),
        sa.ForeignKeyConstraint(
            ["calendar_version"],
            ["calendar_versions.calendar_version"],
            name=op.f("fk_calendar_sessions_calendar_version_calendar_versions"),
        ),
        sa.PrimaryKeyConstraint(
            "calendar_version", "session_label", name=op.f("pk_calendar_sessions")
        ),
    )
    op.create_table(
        "corporate_action_revisions",
        sa.Column("action_revision_id", sa.String(length=64), nullable=False),
        sa.Column("action_id", sa.String(length=64), nullable=False),
        sa.Column("instrument_id", sa.String(length=64), nullable=False),
        sa.Column("action_type", sa.String(length=24), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("announced_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("effective_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("terms", sa.JSON(), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.CheckConstraint(
            "action_type IN ('split', 'cash_dividend', 'merger', 'symbol_change', 'delisting')",
            name=op.f("ck_corporate_action_revisions_corporate_action_revisions_valid_type"),
        ),
        sa.CheckConstraint(
            "length(payload_hash) = 64",
            name=op.f("ck_corporate_action_revisions_corporate_action_revisions_hash_length"),
        ),
        sa.CheckConstraint(
            "revision >= 1",
            name=op.f("ck_corporate_action_revisions_corporate_action_revisions_positive_revision"),
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.instrument_id"],
            name=op.f("fk_corporate_action_revisions_instrument_id_instruments"),
        ),
        sa.PrimaryKeyConstraint("action_revision_id", name=op.f("pk_corporate_action_revisions")),
        sa.UniqueConstraint(
            "action_id", "revision", name="uq_corporate_action_revisions_action_revision"
        ),
    )
    op.create_index(
        op.f("ix_corporate_action_revisions_instrument_id"),
        "corporate_action_revisions",
        ["instrument_id"],
        unique=False,
    )
    op.create_table(
        "dataset_manifests",
        sa.Column("manifest_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("manifest_hash", sa.String(length=64), nullable=False),
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("schema_version", sa.String(length=32), nullable=False),
        sa.Column("calendar_version", sa.String(length=64), nullable=False),
        sa.Column("universe_version", sa.String(length=64), nullable=False),
        sa.Column("corporate_action_version", sa.String(length=64), nullable=False),
        sa.Column("revision_policy", sa.String(length=24), nullable=False),
        sa.Column("price_basis", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("row_count", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "price_basis = 'raw'",
            name=op.f("ck_dataset_manifests_dataset_manifests_raw_price_only"),
        ),
        sa.CheckConstraint(
            "revision_policy IN ('first_seen', 'revised_as_of')",
            name=op.f("ck_dataset_manifests_dataset_manifests_valid_revision_policy"),
        ),
        sa.CheckConstraint(
            "length(manifest_id) = 64 AND length(manifest_hash) = 64",
            name=op.f("ck_dataset_manifests_dataset_manifests_hash_lengths"),
        ),
        sa.CheckConstraint(
            "row_count > 0", name=op.f("ck_dataset_manifests_dataset_manifests_positive_rows")
        ),
        sa.ForeignKeyConstraint(
            ["calendar_version"],
            ["calendar_versions.calendar_version"],
            name=op.f("fk_dataset_manifests_calendar_version_calendar_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["corporate_action_version"],
            ["corporate_action_sets.corporate_action_version"],
            name=op.f("fk_dataset_manifests_corporate_action_version_corporate_action_sets"),
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["market_data_sources.source_id"],
            name=op.f("fk_dataset_manifests_source_id_market_data_sources"),
        ),
        sa.ForeignKeyConstraint(
            ["universe_version"],
            ["universe_versions.universe_version"],
            name=op.f("fk_dataset_manifests_universe_version_universe_versions"),
        ),
        sa.PrimaryKeyConstraint("manifest_id", name=op.f("pk_dataset_manifests")),
        sa.UniqueConstraint("manifest_hash", name=op.f("uq_dataset_manifests_manifest_hash")),
    )
    op.create_table(
        "ingestion_jobs",
        sa.Column("job_id", sa.String(length=64), nullable=False),
        sa.Column("idempotency_key", sa.String(length=64), nullable=False),
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("source_checksum", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source_record_count", sa.Integer(), nullable=False),
        sa.Column("normalized_record_count", sa.Integer(), nullable=False),
        sa.Column("published_partition_count", sa.Integer(), nullable=False),
        sa.Column("quarantined_record_count", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.String(length=512), nullable=True),
        sa.CheckConstraint(
            "status IN ('completed', 'completed_with_issues', 'failed')",
            name=op.f("ck_ingestion_jobs_ingestion_jobs_valid_status"),
        ),
        sa.CheckConstraint(
            "length(idempotency_key) = 64 AND length(source_checksum) = 64",
            name=op.f("ck_ingestion_jobs_ingestion_jobs_hash_lengths"),
        ),
        sa.CheckConstraint(
            "source_record_count >= 0 AND normalized_record_count >= 0 AND published_partition_count >= 0 AND quarantined_record_count >= 0",
            name=op.f("ck_ingestion_jobs_ingestion_jobs_non_negative_counts"),
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["market_data_sources.source_id"],
            name=op.f("fk_ingestion_jobs_source_id_market_data_sources"),
        ),
        sa.PrimaryKeyConstraint("job_id", name=op.f("pk_ingestion_jobs")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_ingestion_jobs_idempotency_key")),
    )
    op.create_index(
        op.f("ix_ingestion_jobs_source_id"), "ingestion_jobs", ["source_id"], unique=False
    )
    op.create_table(
        "instrument_identifiers",
        sa.Column("identifier_id", sa.String(length=64), nullable=False),
        sa.Column("instrument_id", sa.String(length=64), nullable=False),
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("venue", sa.String(length=16), nullable=False),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("effective_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("tradable", sa.Boolean(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "effective_to IS NULL OR effective_to > effective_from",
            name=op.f("ck_instrument_identifiers_instrument_identifiers_valid_range"),
        ),
        sa.CheckConstraint(
            "revision >= 1",
            name=op.f("ck_instrument_identifiers_instrument_identifiers_positive_revision"),
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.instrument_id"],
            name=op.f("fk_instrument_identifiers_instrument_id_instruments"),
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["market_data_sources.source_id"],
            name=op.f("fk_instrument_identifiers_source_id_market_data_sources"),
        ),
        sa.PrimaryKeyConstraint("identifier_id", name=op.f("pk_instrument_identifiers")),
        sa.UniqueConstraint(
            "source_id",
            "symbol",
            "venue",
            "effective_from",
            "revision",
            name="uq_instrument_identifiers_source_symbol_effective_revision",
        ),
    )
    op.create_index(
        op.f("ix_instrument_identifiers_instrument_id"),
        "instrument_identifiers",
        ["instrument_id"],
        unique=False,
    )
    op.create_table(
        "market_data_entitlements",
        sa.Column("entitlement_id", sa.String(length=64), nullable=False),
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("scope", sa.String(length=256), nullable=False),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("effective_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("terms_digest", sa.String(length=64), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('fixture_only', 'active', 'expired', 'revoked')",
            name=op.f("ck_market_data_entitlements_market_data_entitlements_valid_status"),
        ),
        sa.CheckConstraint(
            "effective_to IS NULL OR effective_to > effective_from",
            name=op.f("ck_market_data_entitlements_market_data_entitlements_valid_range"),
        ),
        sa.CheckConstraint(
            "length(terms_digest) = 64",
            name=op.f("ck_market_data_entitlements_market_data_entitlements_digest_length"),
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["market_data_sources.source_id"],
            name=op.f("fk_market_data_entitlements_source_id_market_data_sources"),
        ),
        sa.PrimaryKeyConstraint("entitlement_id", name=op.f("pk_market_data_entitlements")),
    )
    op.create_index(
        op.f("ix_market_data_entitlements_source_id"),
        "market_data_entitlements",
        ["source_id"],
        unique=False,
    )
    op.create_table(
        "universe_memberships",
        sa.Column("universe_version", sa.String(length=64), nullable=False),
        sa.Column("instrument_id", sa.String(length=64), nullable=False),
        sa.Column("included_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("included_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "included_to IS NULL OR included_to > included_from",
            name=op.f("ck_universe_memberships_universe_memberships_valid_range"),
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.instrument_id"],
            name=op.f("fk_universe_memberships_instrument_id_instruments"),
        ),
        sa.ForeignKeyConstraint(
            ["universe_version"],
            ["universe_versions.universe_version"],
            name=op.f("fk_universe_memberships_universe_version_universe_versions"),
        ),
        sa.PrimaryKeyConstraint(
            "universe_version", "instrument_id", name=op.f("pk_universe_memberships")
        ),
    )
    op.create_table(
        "corporate_action_set_members",
        sa.Column("corporate_action_version", sa.String(length=64), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("action_revision_id", sa.String(length=64), nullable=False),
        sa.CheckConstraint(
            "ordinal >= 0",
            name=op.f(
                "ck_corporate_action_set_members_corporate_action_set_members_non_negative_ordinal"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["action_revision_id"],
            ["corporate_action_revisions.action_revision_id"],
            name=op.f(
                "fk_corporate_action_set_members_action_revision_id_corporate_action_revisions"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["corporate_action_version"],
            ["corporate_action_sets.corporate_action_version"],
            name=op.f(
                "fk_corporate_action_set_members_corporate_action_version_corporate_action_sets"
            ),
        ),
        sa.PrimaryKeyConstraint(
            "corporate_action_version", "ordinal", name=op.f("pk_corporate_action_set_members")
        ),
        sa.UniqueConstraint(
            "corporate_action_version",
            "action_revision_id",
            name="uq_corporate_action_set_members_action",
        ),
    )
    op.create_table(
        "data_quality_runs",
        sa.Column("quality_run_id", sa.String(length=64), nullable=False),
        sa.Column("job_id", sa.String(length=64), nullable=False),
        sa.Column("ruleset_version", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('passed', 'warning', 'failed')",
            name=op.f("ck_data_quality_runs_data_quality_runs_valid_status"),
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["ingestion_jobs.job_id"],
            name=op.f("fk_data_quality_runs_job_id_ingestion_jobs"),
        ),
        sa.PrimaryKeyConstraint("quality_run_id", name=op.f("pk_data_quality_runs")),
        sa.UniqueConstraint("job_id", name=op.f("uq_data_quality_runs_job_id")),
    )
    op.create_table(
        "dataset_partitions",
        sa.Column("partition_id", sa.String(length=64), nullable=False),
        sa.Column("object_id", sa.String(length=64), nullable=False),
        sa.Column("job_id", sa.String(length=64), nullable=False),
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("layer", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("schema_version", sa.String(length=32), nullable=False),
        sa.Column("price_basis", sa.String(length=16), nullable=False),
        sa.Column("row_count", sa.Integer(), nullable=False),
        sa.Column("event_time_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("event_time_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("available_at_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("available_at_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("semantic_checksum", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "layer IN ('raw', 'normalized')",
            name=op.f("ck_dataset_partitions_dataset_partitions_valid_layer"),
        ),
        sa.CheckConstraint(
            "price_basis = 'raw'",
            name=op.f("ck_dataset_partitions_dataset_partitions_raw_price_only"),
        ),
        sa.CheckConstraint(
            "status IN ('published', 'quarantined')",
            name=op.f("ck_dataset_partitions_dataset_partitions_valid_status"),
        ),
        sa.CheckConstraint(
            "event_time_end >= event_time_start AND available_at_end >= available_at_start",
            name=op.f("ck_dataset_partitions_dataset_partitions_valid_ranges"),
        ),
        sa.CheckConstraint(
            "length(partition_id) = 64 AND length(semantic_checksum) = 64",
            name=op.f("ck_dataset_partitions_dataset_partitions_hash_lengths"),
        ),
        sa.CheckConstraint(
            "row_count > 0", name=op.f("ck_dataset_partitions_dataset_partitions_positive_rows")
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["ingestion_jobs.job_id"],
            name=op.f("fk_dataset_partitions_job_id_ingestion_jobs"),
        ),
        sa.ForeignKeyConstraint(
            ["object_id"],
            ["data_objects.object_id"],
            name=op.f("fk_dataset_partitions_object_id_data_objects"),
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["market_data_sources.source_id"],
            name=op.f("fk_dataset_partitions_source_id_market_data_sources"),
        ),
        sa.PrimaryKeyConstraint("partition_id", name=op.f("pk_dataset_partitions")),
        sa.UniqueConstraint(
            "layer", "semantic_checksum", name="uq_dataset_partitions_layer_semantic_checksum"
        ),
    )
    op.create_index(
        op.f("ix_dataset_partitions_job_id"), "dataset_partitions", ["job_id"], unique=False
    )
    op.create_table(
        "data_quality_issues",
        sa.Column("issue_id", sa.String(length=64), nullable=False),
        sa.Column("quality_run_id", sa.String(length=64), nullable=False),
        sa.Column("partition_id", sa.String(length=64), nullable=True),
        sa.Column("instrument_id", sa.String(length=64), nullable=True),
        sa.Column("record_key", sa.String(length=160), nullable=True),
        sa.Column("session_label", sa.String(length=10), nullable=True),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("summary", sa.String(length=160), nullable=False),
        sa.Column("detail", sa.String(length=1024), nullable=False),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("quarantined", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "severity IN ('info', 'warning', 'error')",
            name=op.f("ck_data_quality_issues_data_quality_issues_valid_severity"),
        ),
        sa.CheckConstraint(
            "status = 'open'", name=op.f("ck_data_quality_issues_data_quality_issues_open_only")
        ),
        sa.ForeignKeyConstraint(
            ["quality_run_id"],
            ["data_quality_runs.quality_run_id"],
            name=op.f("fk_data_quality_issues_quality_run_id_data_quality_runs"),
        ),
        sa.PrimaryKeyConstraint("issue_id", name=op.f("pk_data_quality_issues")),
    )
    op.create_index(
        op.f("ix_data_quality_issues_quality_run_id"),
        "data_quality_issues",
        ["quality_run_id"],
        unique=False,
    )
    op.create_table(
        "dataset_manifest_partitions",
        sa.Column("manifest_id", sa.String(length=64), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("partition_id", sa.String(length=64), nullable=False),
        sa.CheckConstraint(
            "ordinal >= 0",
            name=op.f(
                "ck_dataset_manifest_partitions_dataset_manifest_partitions_non_negative_ordinal"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["manifest_id"],
            ["dataset_manifests.manifest_id"],
            name=op.f("fk_dataset_manifest_partitions_manifest_id_dataset_manifests"),
        ),
        sa.ForeignKeyConstraint(
            ["partition_id"],
            ["dataset_partitions.partition_id"],
            name=op.f("fk_dataset_manifest_partitions_partition_id_dataset_partitions"),
        ),
        sa.PrimaryKeyConstraint(
            "manifest_id", "ordinal", name=op.f("pk_dataset_manifest_partitions")
        ),
        sa.UniqueConstraint(
            "manifest_id", "partition_id", name="uq_dataset_manifest_partitions_partition"
        ),
    )
    op.create_table(
        "partition_quarantines",
        sa.Column("partition_id", sa.String(length=64), nullable=False),
        sa.Column("reason", sa.String(length=512), nullable=False),
        sa.Column("quarantined_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("row_count", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "row_count > 0",
            name=op.f("ck_partition_quarantines_partition_quarantines_positive_rows"),
        ),
        sa.ForeignKeyConstraint(
            ["partition_id"],
            ["dataset_partitions.partition_id"],
            name=op.f("fk_partition_quarantines_partition_id_dataset_partitions"),
        ),
        sa.PrimaryKeyConstraint("partition_id", name=op.f("pk_partition_quarantines")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("partition_quarantines")
    op.drop_table("dataset_manifest_partitions")
    op.drop_index(op.f("ix_data_quality_issues_quality_run_id"), table_name="data_quality_issues")
    op.drop_table("data_quality_issues")
    op.drop_index(op.f("ix_dataset_partitions_job_id"), table_name="dataset_partitions")
    op.drop_table("dataset_partitions")
    op.drop_table("data_quality_runs")
    op.drop_table("corporate_action_set_members")
    op.drop_table("universe_memberships")
    op.drop_index(
        op.f("ix_market_data_entitlements_source_id"), table_name="market_data_entitlements"
    )
    op.drop_table("market_data_entitlements")
    op.drop_index(
        op.f("ix_instrument_identifiers_instrument_id"), table_name="instrument_identifiers"
    )
    op.drop_table("instrument_identifiers")
    op.drop_index(op.f("ix_ingestion_jobs_source_id"), table_name="ingestion_jobs")
    op.drop_table("ingestion_jobs")
    op.drop_table("dataset_manifests")
    op.drop_index(
        op.f("ix_corporate_action_revisions_instrument_id"), table_name="corporate_action_revisions"
    )
    op.drop_table("corporate_action_revisions")
    op.drop_table("calendar_sessions")
    op.drop_table("universe_versions")
    op.drop_table("market_data_sources")
    op.drop_table("instruments")
    op.drop_table("data_objects")
    op.drop_table("corporate_action_sets")
    op.drop_table("calendar_versions")
    # ### end Alembic commands ###
