"""Add the independent Phase 2 durable execution foundation.

Revision ID: 0007_phase2_durability
Revises: 0006_replay_run_manifests
Create Date: 2026-07-20
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0007_phase2_durability"
down_revision: str | None = "0006_replay_run_manifests"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "phase2_account_leases",
        sa.Column("lease_sha256", sa.String(length=64), nullable=False),
        sa.Column("account_id", sa.String(length=64), nullable=False),
        sa.Column("owner_id", sa.String(length=128), nullable=False),
        sa.Column("lease_id", sa.String(length=64), nullable=False),
        sa.Column("fencing_generation", sa.BigInteger(), nullable=False),
        sa.Column("acquired_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("policy_sha256", sa.String(length=64), nullable=False),
        sa.Column("canonical_payload", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "fencing_generation > 0", name=op.f("ck_phase2_account_leases_positive_generation")
        ),
        sa.CheckConstraint(
            "heartbeat_at >= acquired_at AND expires_at > heartbeat_at",
            name=op.f("ck_phase2_account_leases_valid_time_range"),
        ),
        sa.CheckConstraint(
            "length(canonical_payload) BETWEEN 2 AND 65536",
            name=op.f("ck_phase2_account_leases_payload_size"),
        ),
        sa.CheckConstraint(
            "length(lease_sha256) = 64 AND length(policy_sha256) = 64",
            name=op.f("ck_phase2_account_leases_hash_lengths"),
        ),
        sa.PrimaryKeyConstraint("lease_sha256", name=op.f("pk_phase2_account_leases")),
        sa.UniqueConstraint(
            "account_id", "fencing_generation", "lease_sha256", name="account_generation_digest"
        ),
        sa.UniqueConstraint(
            "account_id", "lease_id", "heartbeat_at", name="account_lease_revision"
        ),
    )
    op.create_index(
        "ix_phase2_account_leases_account_generation",
        "phase2_account_leases",
        ["account_id", "fencing_generation"],
        unique=False,
    )
    op.create_table(
        "phase2_ledger_entries",
        sa.Column("entry_id", sa.String(length=64), nullable=False),
        sa.Column("account_id", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("reference_id", sa.String(length=128), nullable=False),
        sa.Column("source_sha256", sa.String(length=64), nullable=False),
        sa.Column("effective_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("canonical_payload", sa.Text(), nullable=False),
        sa.Column("semantic_sha256", sa.String(length=64), nullable=False),
        sa.CheckConstraint(
            "kind IN ('cash_flow', 'execution', 'execution_correction', 'settlement_reclassification', 'execution_settlement', 'stock_split', 'cash_dividend_accrual', 'cash_dividend_payment')",
            name=op.f("ck_phase2_ledger_entries_valid_kind"),
        ),
        sa.CheckConstraint(
            "length(canonical_payload) BETWEEN 2 AND 524288",
            name=op.f("ck_phase2_ledger_entries_payload_size"),
        ),
        sa.CheckConstraint(
            "length(source_sha256) = 64 AND length(semantic_sha256) = 64",
            name=op.f("ck_phase2_ledger_entries_hash_lengths"),
        ),
        sa.CheckConstraint(
            "recorded_at >= effective_at", name=op.f("ck_phase2_ledger_entries_valid_time_order")
        ),
        sa.PrimaryKeyConstraint("entry_id", name=op.f("pk_phase2_ledger_entries")),
        sa.UniqueConstraint("account_id", "kind", "reference_id", name="account_fact"),
        sa.UniqueConstraint(
            "semantic_sha256", name=op.f("uq_phase2_ledger_entries_semantic_sha256")
        ),
    )
    op.create_index(
        "ix_phase2_ledger_entries_account_effective",
        "phase2_ledger_entries",
        ["account_id", "effective_at"],
        unique=False,
    )
    op.create_table(
        "phase2_account_lease_heads",
        sa.Column("account_id", sa.String(length=64), nullable=False),
        sa.Column("last_fencing_generation", sa.BigInteger(), nullable=False),
        sa.Column("current_fencing_generation", sa.BigInteger(), nullable=True),
        sa.Column("current_lease_sha256", sa.String(length=64), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(current_fencing_generation IS NULL AND current_lease_sha256 IS NULL) OR (current_fencing_generation IS NOT NULL AND current_lease_sha256 IS NOT NULL AND current_fencing_generation = last_fencing_generation)",
            name=op.f("ck_phase2_account_lease_heads_current_lease_pair"),
        ),
        sa.CheckConstraint(
            "current_lease_sha256 IS NULL OR length(current_lease_sha256) = 64",
            name=op.f("ck_phase2_account_lease_heads_current_hash_length"),
        ),
        sa.CheckConstraint(
            "last_fencing_generation >= 0",
            name=op.f("ck_phase2_account_lease_heads_non_negative_generation"),
        ),
        sa.ForeignKeyConstraint(
            ["account_id", "current_fencing_generation", "current_lease_sha256"],
            [
                "phase2_account_leases.account_id",
                "phase2_account_leases.fencing_generation",
                "phase2_account_leases.lease_sha256",
            ],
            name="current_lease",
        ),
        sa.PrimaryKeyConstraint("account_id", name=op.f("pk_phase2_account_lease_heads")),
    )
    op.create_table(
        "phase2_account_lease_releases",
        sa.Column("release_id", sa.String(length=64), nullable=False),
        sa.Column("release_sha256", sa.String(length=64), nullable=False),
        sa.Column("account_id", sa.String(length=64), nullable=False),
        sa.Column("owner_id", sa.String(length=128), nullable=False),
        sa.Column("lease_id", sa.String(length=64), nullable=False),
        sa.Column("fencing_generation", sa.BigInteger(), nullable=False),
        sa.Column("lease_sha256", sa.String(length=64), nullable=False),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("policy_sha256", sa.String(length=64), nullable=False),
        sa.Column("canonical_payload", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "fencing_generation > 0",
            name=op.f("ck_phase2_account_lease_releases_positive_generation"),
        ),
        sa.CheckConstraint(
            "length(canonical_payload) BETWEEN 2 AND 65536",
            name=op.f("ck_phase2_account_lease_releases_payload_size"),
        ),
        sa.CheckConstraint(
            "length(release_sha256) = 64 AND length(lease_sha256) = 64 AND length(policy_sha256) = 64",
            name=op.f("ck_phase2_account_lease_releases_hash_lengths"),
        ),
        sa.ForeignKeyConstraint(
            ["account_id", "fencing_generation", "lease_sha256"],
            [
                "phase2_account_leases.account_id",
                "phase2_account_leases.fencing_generation",
                "phase2_account_leases.lease_sha256",
            ],
            name="released_lease",
        ),
        sa.PrimaryKeyConstraint("release_id", name=op.f("pk_phase2_account_lease_releases")),
        sa.UniqueConstraint(
            "lease_sha256", name=op.f("uq_phase2_account_lease_releases_lease_sha256")
        ),
        sa.UniqueConstraint(
            "release_sha256", name=op.f("uq_phase2_account_lease_releases_release_sha256")
        ),
    )
    op.create_index(
        "ix_phase2_account_lease_releases_account_generation",
        "phase2_account_lease_releases",
        ["account_id", "fencing_generation"],
        unique=False,
    )
    op.create_table(
        "phase2_batch_decisions",
        sa.Column("decision_id", sa.String(length=64), nullable=False),
        sa.Column("intent_batch_id", sa.String(length=64), nullable=False),
        sa.Column("intent_batch_sha256", sa.String(length=64), nullable=False),
        sa.Column("account_id", sa.String(length=64), nullable=False),
        sa.Column("account_observation_sequence", sa.BigInteger(), nullable=False),
        sa.Column("fencing_generation", sa.BigInteger(), nullable=False),
        sa.Column("lease_sha256", sa.String(length=64), nullable=False),
        sa.Column("fence_sha256", sa.String(length=64), nullable=False),
        sa.Column("snapshot_version", sa.String(length=64), nullable=False),
        sa.Column("snapshot_sha256", sa.String(length=64), nullable=False),
        sa.Column("active_capacity_payload", sa.Text(), nullable=False),
        sa.Column("active_capacity_sha256", sa.String(length=64), nullable=False),
        sa.Column("policy_id", sa.String(length=64), nullable=False),
        sa.Column("policy_version", sa.String(length=64), nullable=False),
        sa.Column("policy_sha256", sa.String(length=64), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("evaluated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("intent_count", sa.Integer(), nullable=False),
        sa.Column("rules_payload", sa.Text(), nullable=False),
        sa.Column("canonical_payload", sa.Text(), nullable=False),
        sa.Column("semantic_sha256", sa.String(length=64), nullable=False),
        sa.CheckConstraint(
            "(status = 'no_action' AND intent_count = 0) OR (status IN ('approved', 'rejected') AND intent_count > 0)",
            name=op.f("ck_phase2_batch_decisions_status_matches_count"),
        ),
        sa.CheckConstraint(
            "status IN ('approved', 'rejected', 'no_action')",
            name=op.f("ck_phase2_batch_decisions_valid_status"),
        ),
        sa.CheckConstraint(
            "expires_at > evaluated_at", name=op.f("ck_phase2_batch_decisions_positive_ttl")
        ),
        sa.CheckConstraint(
            "fencing_generation > 0", name=op.f("ck_phase2_batch_decisions_positive_generation")
        ),
        sa.CheckConstraint(
            "account_observation_sequence > 0",
            name=op.f("ck_phase2_batch_decisions_positive_observation_sequence"),
        ),
        sa.CheckConstraint(
            "length(currency) = 3 AND currency = upper(currency)",
            name=op.f("ck_phase2_batch_decisions_canonical_currency"),
        ),
        sa.CheckConstraint(
            "length(intent_batch_sha256) = 64 AND length(lease_sha256) = 64 AND length(fence_sha256) = 64 AND length(snapshot_sha256) = 64 AND length(active_capacity_sha256) = 64 AND length(policy_sha256) = 64 AND length(semantic_sha256) = 64",
            name=op.f("ck_phase2_batch_decisions_hash_lengths"),
        ),
        sa.CheckConstraint(
            "length(rules_payload) BETWEEN 2 AND 262144 AND length(active_capacity_payload) BETWEEN 2 AND 1048576 AND length(canonical_payload) BETWEEN 2 AND 1048576",
            name=op.f("ck_phase2_batch_decisions_payload_sizes"),
        ),
        sa.ForeignKeyConstraint(
            ["account_id", "fencing_generation", "lease_sha256"],
            [
                "phase2_account_leases.account_id",
                "phase2_account_leases.fencing_generation",
                "phase2_account_leases.lease_sha256",
            ],
            name="authorizing_lease",
        ),
        sa.PrimaryKeyConstraint("decision_id", name=op.f("pk_phase2_batch_decisions")),
        sa.UniqueConstraint(
            "decision_id", "account_id", "fencing_generation", name="decision_account_generation"
        ),
        sa.UniqueConstraint(
            "account_id",
            "account_observation_sequence",
            name="account_observation_sequence",
        ),
        sa.UniqueConstraint(
            "intent_batch_id", name=op.f("uq_phase2_batch_decisions_intent_batch_id")
        ),
        sa.UniqueConstraint(
            "semantic_sha256", name=op.f("uq_phase2_batch_decisions_semantic_sha256")
        ),
    )
    op.create_index(
        "ix_phase2_batch_decisions_account_evaluated",
        "phase2_batch_decisions",
        ["account_id", "evaluated_at"],
        unique=False,
    )
    op.create_table(
        "phase2_batch_members",
        sa.Column("membership_id", sa.String(length=64), nullable=False),
        sa.Column("decision_id", sa.String(length=64), nullable=False),
        sa.Column("intent_batch_id", sa.String(length=64), nullable=False),
        sa.Column("intent_batch_sha256", sa.String(length=64), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("intent_id", sa.String(length=64), nullable=False),
        sa.Column("intent_payload_sha256", sa.String(length=64), nullable=False),
        sa.Column("canonical_payload", sa.Text(), nullable=False),
        sa.Column("semantic_sha256", sa.String(length=64), nullable=False),
        sa.CheckConstraint(
            "length(intent_batch_sha256) = 64 "
            "AND length(intent_payload_sha256) = 64 "
            "AND length(semantic_sha256) = 64",
            name=op.f("ck_phase2_batch_members_hash_lengths"),
        ),
        sa.CheckConstraint(
            "ordinal >= 0",
            name=op.f("ck_phase2_batch_members_non_negative_ordinal"),
        ),
        sa.CheckConstraint(
            "length(canonical_payload) BETWEEN 2 AND 262144",
            name=op.f("ck_phase2_batch_members_payload_size"),
        ),
        sa.ForeignKeyConstraint(
            ["decision_id"],
            ["phase2_batch_decisions.decision_id"],
            name=op.f("fk_phase2_batch_members_decision_id_phase2_batch_decisions"),
        ),
        sa.PrimaryKeyConstraint("membership_id", name=op.f("pk_phase2_batch_members")),
        sa.UniqueConstraint(
            "decision_id",
            "intent_id",
            name="batch_member_decision_intent",
        ),
        sa.UniqueConstraint("decision_id", "ordinal", name="decision_ordinal"),
        sa.UniqueConstraint("intent_id", name=op.f("uq_phase2_batch_members_intent_id")),
        sa.UniqueConstraint(
            "semantic_sha256", name=op.f("uq_phase2_batch_members_semantic_sha256")
        ),
    )
    op.create_index(
        "ix_phase2_batch_members_batch_ordinal",
        "phase2_batch_members",
        ["intent_batch_id", "ordinal"],
        unique=False,
    )
    op.create_table(
        "phase2_ledger_postings",
        sa.Column(
            "posting_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("entry_id", sa.String(length=64), nullable=False),
        sa.Column("line_number", sa.Integer(), nullable=False),
        sa.Column("account", sa.String(length=128), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("debit", sa.Numeric(precision=28, scale=10), server_default="0", nullable=False),
        sa.Column("credit", sa.Numeric(precision=28, scale=10), server_default="0", nullable=False),
        sa.Column(
            "units_delta", sa.Numeric(precision=28, scale=10), server_default="0", nullable=False
        ),
        sa.Column("instrument_id", sa.String(length=64), nullable=True),
        sa.Column("semantic_sha256", sa.String(length=64), nullable=False),
        sa.CheckConstraint(
            "NOT (debit = 0 AND credit = 0 AND units_delta = 0)",
            name=op.f("ck_phase2_ledger_postings_non_empty_posting"),
        ),
        sa.CheckConstraint(
            "debit = 0 OR credit = 0", name=op.f("ck_phase2_ledger_postings_single_money_side")
        ),
        sa.CheckConstraint(
            "debit >= 0 AND credit >= 0", name=op.f("ck_phase2_ledger_postings_non_negative_money")
        ),
        sa.CheckConstraint(
            "length(currency) = 3 AND currency = upper(currency)",
            name=op.f("ck_phase2_ledger_postings_canonical_currency"),
        ),
        sa.CheckConstraint(
            "length(semantic_sha256) = 64",
            name=op.f("ck_phase2_ledger_postings_semantic_hash_length"),
        ),
        sa.CheckConstraint(
            "line_number > 0", name=op.f("ck_phase2_ledger_postings_positive_line_number")
        ),
        sa.CheckConstraint(
            "units_delta = 0 OR (instrument_id IS NOT NULL AND units_delta = CAST(units_delta AS BIGINT))",
            name=op.f("ck_phase2_ledger_postings_valid_units"),
        ),
        sa.ForeignKeyConstraint(
            ["entry_id"],
            ["phase2_ledger_entries.entry_id"],
            name=op.f("fk_phase2_ledger_postings_entry_id_phase2_ledger_entries"),
        ),
        sa.PrimaryKeyConstraint("posting_id", name=op.f("pk_phase2_ledger_postings")),
        sa.UniqueConstraint("entry_id", "line_number", name="entry_line"),
        sa.UniqueConstraint("entry_id", "semantic_sha256", name="entry_posting_digest"),
    )
    op.create_index(
        "ix_phase2_ledger_postings_entry_id", "phase2_ledger_postings", ["entry_id"], unique=False
    )
    op.create_table(
        "phase2_batch_reservations",
        sa.Column("reservation_id", sa.String(length=64), nullable=False),
        sa.Column("parent_decision_id", sa.String(length=64), nullable=False),
        sa.Column("intent_batch_id", sa.String(length=64), nullable=False),
        sa.Column("intent_batch_sha256", sa.String(length=64), nullable=False),
        sa.Column("account_id", sa.String(length=64), nullable=False),
        sa.Column("fencing_generation", sa.BigInteger(), nullable=False),
        sa.Column("lease_sha256", sa.String(length=64), nullable=False),
        sa.Column("fence_sha256", sa.String(length=64), nullable=False),
        sa.Column("snapshot_sha256", sa.String(length=64), nullable=False),
        sa.Column("policy_sha256", sa.String(length=64), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("state", sa.String(length=24), nullable=False),
        sa.Column("state_version", sa.BigInteger(), server_default="1", nullable=False),
        sa.Column("authorization_count", sa.Integer(), nullable=False),
        sa.Column("remaining_authorization_count", sa.Integer(), nullable=False),
        sa.Column("initial_cash", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("initial_buy_exposure", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("remaining_cash", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("remaining_buy_exposure", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("canonical_payload", sa.Text(), nullable=False),
        sa.Column("semantic_sha256", sa.String(length=64), nullable=False),
        sa.CheckConstraint(
            "(state = 'released' AND released_at IS NOT NULL AND remaining_authorization_count = 0 AND remaining_cash = 0 AND remaining_buy_exposure = 0) OR (state <> 'released' AND released_at IS NULL)",
            name=op.f("ck_phase2_batch_reservations_released_state"),
        ),
        sa.CheckConstraint(
            "state IN ('active', 'partially_released', 'frozen', 'released')",
            name=op.f("ck_phase2_batch_reservations_valid_state"),
        ),
        sa.CheckConstraint(
            "authorization_count > 0 AND remaining_authorization_count >= 0 AND remaining_authorization_count <= authorization_count",
            name=op.f("ck_phase2_batch_reservations_valid_authorization_counts"),
        ),
        sa.CheckConstraint(
            "expires_at > created_at", name=op.f("ck_phase2_batch_reservations_positive_ttl")
        ),
        sa.CheckConstraint(
            "fencing_generation > 0", name=op.f("ck_phase2_batch_reservations_positive_generation")
        ),
        sa.CheckConstraint(
            "initial_cash >= 0 AND initial_buy_exposure >= 0 AND remaining_cash >= 0 AND remaining_cash <= initial_cash AND remaining_buy_exposure >= 0 AND remaining_buy_exposure <= initial_buy_exposure",
            name=op.f("ck_phase2_batch_reservations_conserved_amounts"),
        ),
        sa.CheckConstraint(
            "length(canonical_payload) BETWEEN 2 AND 1048576",
            name=op.f("ck_phase2_batch_reservations_payload_size"),
        ),
        sa.CheckConstraint(
            "length(currency) = 3 AND currency = upper(currency)",
            name=op.f("ck_phase2_batch_reservations_canonical_currency"),
        ),
        sa.CheckConstraint(
            "length(intent_batch_sha256) = 64 AND length(lease_sha256) = 64 AND length(fence_sha256) = 64 AND length(snapshot_sha256) = 64 AND length(policy_sha256) = 64 AND length(semantic_sha256) = 64",
            name=op.f("ck_phase2_batch_reservations_hash_lengths"),
        ),
        sa.CheckConstraint(
            "state_version > 0", name=op.f("ck_phase2_batch_reservations_positive_state_version")
        ),
        sa.ForeignKeyConstraint(
            ["account_id", "fencing_generation", "lease_sha256"],
            [
                "phase2_account_leases.account_id",
                "phase2_account_leases.fencing_generation",
                "phase2_account_leases.lease_sha256",
            ],
            name="authorizing_lease",
        ),
        sa.ForeignKeyConstraint(
            ["parent_decision_id"],
            ["phase2_batch_decisions.decision_id"],
            name=op.f("fk_phase2_batch_reservations_parent_decision_id_phase2_batch_decisions"),
        ),
        sa.PrimaryKeyConstraint("reservation_id", name=op.f("pk_phase2_batch_reservations")),
        sa.UniqueConstraint(
            "intent_batch_id", name=op.f("uq_phase2_batch_reservations_intent_batch_id")
        ),
        sa.UniqueConstraint(
            "parent_decision_id", name=op.f("uq_phase2_batch_reservations_parent_decision_id")
        ),
        sa.UniqueConstraint("reservation_id", "parent_decision_id", name="reservation_parent"),
        sa.UniqueConstraint(
            "semantic_sha256", name=op.f("uq_phase2_batch_reservations_semantic_sha256")
        ),
    )
    op.create_index(
        "ix_phase2_batch_reservations_account_state",
        "phase2_batch_reservations",
        ["account_id", "state"],
        unique=False,
    )
    op.create_index(
        "ix_phase2_batch_reservations_expires_at",
        "phase2_batch_reservations",
        ["expires_at"],
        unique=False,
    )
    op.create_table(
        "phase2_batch_authorizations",
        sa.Column("authorization_id", sa.String(length=64), nullable=False),
        sa.Column("parent_decision_id", sa.String(length=64), nullable=False),
        sa.Column("reservation_id", sa.String(length=64), nullable=False),
        sa.Column("intent_batch_id", sa.String(length=64), nullable=False),
        sa.Column("intent_batch_sha256", sa.String(length=64), nullable=False),
        sa.Column("account_id", sa.String(length=64), nullable=False),
        sa.Column("fencing_generation", sa.BigInteger(), nullable=False),
        sa.Column("lease_sha256", sa.String(length=64), nullable=False),
        sa.Column("fence_sha256", sa.String(length=64), nullable=False),
        sa.Column("snapshot_sha256", sa.String(length=64), nullable=False),
        sa.Column("policy_sha256", sa.String(length=64), nullable=False),
        sa.Column("session_sha256", sa.String(length=64), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("intent_id", sa.String(length=64), nullable=False),
        sa.Column("intent_payload_sha256", sa.String(length=64), nullable=False),
        sa.Column("evaluated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("instrument_id", sa.String(length=64), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("side", sa.String(length=8), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("reference_price", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("snapshot_as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reference_event_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("maximum_execution_price", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("maximum_fee", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("maximum_cash_requirement", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("reserved_cash", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("reserved_sell_quantity", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("reserved_buy_exposure", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("canonical_payload", sa.Text(), nullable=False),
        sa.Column("semantic_sha256", sa.String(length=64), nullable=False),
        sa.CheckConstraint(
            "(side = 'buy' AND reserved_sell_quantity = 0 AND reserved_buy_exposure = quantity * maximum_execution_price) OR (side = 'sell' AND reserved_sell_quantity = quantity AND reserved_buy_exposure = 0)",
            name=op.f("ck_phase2_batch_authorizations_side_holds"),
        ),
        sa.CheckConstraint(
            "side IN ('buy', 'sell')", name=op.f("ck_phase2_batch_authorizations_valid_side")
        ),
        sa.CheckConstraint(
            "expires_at > evaluated_at", name=op.f("ck_phase2_batch_authorizations_positive_ttl")
        ),
        sa.CheckConstraint(
            "fencing_generation > 0",
            name=op.f("ck_phase2_batch_authorizations_positive_generation"),
        ),
        sa.CheckConstraint(
            "length(canonical_payload) BETWEEN 2 AND 262144",
            name=op.f("ck_phase2_batch_authorizations_payload_size"),
        ),
        sa.CheckConstraint(
            "length(currency) = 3 AND currency = upper(currency)",
            name=op.f("ck_phase2_batch_authorizations_canonical_currency"),
        ),
        sa.CheckConstraint(
            "length(intent_batch_sha256) = 64 AND length(lease_sha256) = 64 AND length(fence_sha256) = 64 AND length(snapshot_sha256) = 64 AND length(policy_sha256) = 64 AND length(session_sha256) = 64 AND length(intent_payload_sha256) = 64 AND length(semantic_sha256) = 64",
            name=op.f("ck_phase2_batch_authorizations_hash_lengths"),
        ),
        sa.CheckConstraint(
            "maximum_cash_requirement = reserved_cash AND reserved_cash = reserved_buy_exposure + maximum_fee",
            name=op.f("ck_phase2_batch_authorizations_cash_conservation"),
        ),
        sa.CheckConstraint(
            "quantity > 0 AND quantity = CAST(quantity AS BIGINT)",
            name=op.f("ck_phase2_batch_authorizations_whole_quantity"),
        ),
        sa.CheckConstraint(
            "reference_price > 0 AND maximum_execution_price >= reference_price AND maximum_fee >= 0 AND maximum_cash_requirement >= 0 AND reserved_cash >= 0 AND reserved_sell_quantity >= 0 AND reserved_buy_exposure >= 0",
            name=op.f("ck_phase2_batch_authorizations_valid_amounts"),
        ),
        sa.CheckConstraint(
            "symbol = upper(symbol)", name=op.f("ck_phase2_batch_authorizations_canonical_symbol")
        ),
        sa.ForeignKeyConstraint(
            ["account_id", "fencing_generation", "lease_sha256"],
            [
                "phase2_account_leases.account_id",
                "phase2_account_leases.fencing_generation",
                "phase2_account_leases.lease_sha256",
            ],
            name="authorizing_lease",
        ),
        sa.ForeignKeyConstraint(
            ["reservation_id", "parent_decision_id"],
            [
                "phase2_batch_reservations.reservation_id",
                "phase2_batch_reservations.parent_decision_id",
            ],
            name="parent_reservation",
        ),
        sa.PrimaryKeyConstraint("authorization_id", name=op.f("pk_phase2_batch_authorizations")),
        sa.UniqueConstraint("intent_id", name=op.f("uq_phase2_batch_authorizations_intent_id")),
        sa.UniqueConstraint(
            "parent_decision_id",
            "intent_id",
            name="authorization_decision_intent",
        ),
        sa.UniqueConstraint(
            "semantic_sha256", name=op.f("uq_phase2_batch_authorizations_semantic_sha256")
        ),
    )
    op.create_index(
        "ix_phase2_batch_authorizations_account_instrument",
        "phase2_batch_authorizations",
        ["account_id", "instrument_id"],
        unique=False,
    )
    op.create_index(
        "ix_phase2_batch_authorizations_expires_at",
        "phase2_batch_authorizations",
        ["expires_at"],
        unique=False,
    )
    op.create_table(
        "phase2_logical_orders",
        sa.Column("order_id", sa.String(length=64), nullable=False),
        sa.Column("account_id", sa.String(length=64), nullable=False),
        sa.Column("fencing_generation", sa.BigInteger(), nullable=False),
        sa.Column("lease_sha256", sa.String(length=64), nullable=False),
        sa.Column("fence_sha256", sa.String(length=64), nullable=False),
        sa.Column("parent_decision_id", sa.String(length=64), nullable=False),
        sa.Column("reservation_id", sa.String(length=64), nullable=False),
        sa.Column("authorization_id", sa.String(length=64), nullable=False),
        sa.Column("intent_batch_id", sa.String(length=64), nullable=False),
        sa.Column("intent_id", sa.String(length=64), nullable=False),
        sa.Column("intent_payload_sha256", sa.String(length=64), nullable=False),
        sa.Column("intent_payload", sa.Text(), nullable=False),
        sa.Column("submission_attempt_id", sa.String(length=64), nullable=False),
        sa.Column("client_order_id", sa.String(length=64), nullable=False),
        sa.Column("instrument_id", sa.String(length=64), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("side", sa.String(length=8), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("canonical_payload", sa.Text(), nullable=False),
        sa.Column("semantic_sha256", sa.String(length=64), nullable=False),
        sa.CheckConstraint(
            "side IN ('buy', 'sell')", name=op.f("ck_phase2_logical_orders_valid_side")
        ),
        sa.CheckConstraint(
            "fencing_generation > 0", name=op.f("ck_phase2_logical_orders_positive_generation")
        ),
        sa.CheckConstraint(
            "length(intent_payload) BETWEEN 2 AND 262144 AND length(canonical_payload) BETWEEN 2 AND 524288",
            name=op.f("ck_phase2_logical_orders_payload_sizes"),
        ),
        sa.CheckConstraint(
            "length(lease_sha256) = 64 AND length(fence_sha256) = 64 AND length(intent_payload_sha256) = 64 AND length(semantic_sha256) = 64",
            name=op.f("ck_phase2_logical_orders_hash_lengths"),
        ),
        sa.CheckConstraint(
            "quantity > 0 AND quantity = CAST(quantity AS BIGINT)",
            name=op.f("ck_phase2_logical_orders_whole_quantity"),
        ),
        sa.CheckConstraint(
            "symbol = upper(symbol)", name=op.f("ck_phase2_logical_orders_canonical_symbol")
        ),
        sa.ForeignKeyConstraint(
            ["account_id", "fencing_generation", "lease_sha256"],
            [
                "phase2_account_leases.account_id",
                "phase2_account_leases.fencing_generation",
                "phase2_account_leases.lease_sha256",
            ],
            name="authorizing_lease",
        ),
        sa.ForeignKeyConstraint(
            ["authorization_id"],
            ["phase2_batch_authorizations.authorization_id"],
            name=op.f("fk_phase2_logical_orders_authorization_id_phase2_batch_authorizations"),
        ),
        sa.ForeignKeyConstraint(
            ["reservation_id", "parent_decision_id"],
            [
                "phase2_batch_reservations.reservation_id",
                "phase2_batch_reservations.parent_decision_id",
            ],
            name="parent_reservation",
        ),
        sa.PrimaryKeyConstraint("order_id", name=op.f("pk_phase2_logical_orders")),
        sa.UniqueConstraint(
            "authorization_id", name=op.f("uq_phase2_logical_orders_authorization_id")
        ),
        sa.UniqueConstraint(
            "client_order_id", name=op.f("uq_phase2_logical_orders_client_order_id")
        ),
        sa.UniqueConstraint("intent_id", name=op.f("uq_phase2_logical_orders_intent_id")),
        sa.UniqueConstraint(
            "order_id", "account_id", "fencing_generation", name="order_account_generation"
        ),
        sa.UniqueConstraint(
            "semantic_sha256", name=op.f("uq_phase2_logical_orders_semantic_sha256")
        ),
        sa.UniqueConstraint(
            "submission_attempt_id", name=op.f("uq_phase2_logical_orders_submission_attempt_id")
        ),
    )
    op.create_index(
        "ix_phase2_logical_orders_account_submitted",
        "phase2_logical_orders",
        ["account_id", "submitted_at"],
        unique=False,
    )
    op.create_table(
        "phase2_authorization_consumptions",
        sa.Column("consumption_id", sa.String(length=64), nullable=False),
        sa.Column("authorization_id", sa.String(length=64), nullable=False),
        sa.Column("order_id", sa.String(length=64), nullable=False),
        sa.Column("reservation_id", sa.String(length=64), nullable=False),
        sa.Column("intent_id", sa.String(length=64), nullable=False),
        sa.Column("intent_payload_sha256", sa.String(length=64), nullable=False),
        sa.Column("account_id", sa.String(length=64), nullable=False),
        sa.Column("fencing_generation", sa.BigInteger(), nullable=False),
        sa.Column("lease_sha256", sa.String(length=64), nullable=False),
        sa.Column("fence_sha256", sa.String(length=64), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("semantic_sha256", sa.String(length=64), nullable=False),
        sa.CheckConstraint(
            "fencing_generation > 0",
            name=op.f("ck_phase2_authorization_consumptions_positive_generation"),
        ),
        sa.CheckConstraint(
            "length(intent_payload_sha256) = 64 AND length(lease_sha256) = 64 AND length(fence_sha256) = 64 AND length(semantic_sha256) = 64",
            name=op.f("ck_phase2_authorization_consumptions_hash_lengths"),
        ),
        sa.ForeignKeyConstraint(
            ["account_id", "fencing_generation", "lease_sha256"],
            [
                "phase2_account_leases.account_id",
                "phase2_account_leases.fencing_generation",
                "phase2_account_leases.lease_sha256",
            ],
            name="consuming_lease",
        ),
        sa.ForeignKeyConstraint(
            ["authorization_id"],
            ["phase2_batch_authorizations.authorization_id"],
            name=op.f(
                "fk_phase2_authorization_consumptions_authorization_id_phase2_batch_authorizations"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["phase2_logical_orders.order_id"],
            name=op.f("fk_phase2_authorization_consumptions_order_id_phase2_logical_orders"),
        ),
        sa.PrimaryKeyConstraint(
            "consumption_id", name=op.f("pk_phase2_authorization_consumptions")
        ),
        sa.UniqueConstraint(
            "authorization_id", name=op.f("uq_phase2_authorization_consumptions_authorization_id")
        ),
        sa.UniqueConstraint(
            "intent_id", name=op.f("uq_phase2_authorization_consumptions_intent_id")
        ),
        sa.UniqueConstraint("order_id", name=op.f("uq_phase2_authorization_consumptions_order_id")),
        sa.UniqueConstraint(
            "semantic_sha256", name=op.f("uq_phase2_authorization_consumptions_semantic_sha256")
        ),
    )
    op.create_index(
        "ix_phase2_authorization_consumptions_account_time",
        "phase2_authorization_consumptions",
        ["account_id", "consumed_at"],
        unique=False,
    )
    op.create_table(
        "phase2_order_events",
        sa.Column("event_id", sa.String(length=128), nullable=False),
        sa.Column("order_id", sa.String(length=64), nullable=False),
        sa.Column("broker_order_id", sa.String(length=128), nullable=False),
        sa.Column("broker_sequence", sa.Integer(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("reason", sa.String(length=512), nullable=True),
        sa.Column("execution_id", sa.String(length=128), nullable=True),
        sa.Column("execution_revision", sa.Integer(), nullable=True),
        sa.Column("supersedes_event_id", sa.String(length=128), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=28, scale=10), nullable=True),
        sa.Column("price", sa.Numeric(precision=28, scale=10), nullable=True),
        sa.Column("fee", sa.Numeric(precision=28, scale=10), nullable=True),
        sa.Column("canonical_payload", sa.Text(), nullable=False),
        sa.Column("semantic_sha256", sa.String(length=64), nullable=False),
        sa.CheckConstraint(
            "(kind NOT IN ('execution', 'execution_correction') AND execution_id IS NULL AND execution_revision IS NULL AND supersedes_event_id IS NULL AND quantity IS NULL AND price IS NULL AND fee IS NULL) OR (kind = 'execution' AND execution_id IS NOT NULL AND execution_revision = 1 AND supersedes_event_id IS NULL AND quantity > 0 AND quantity = CAST(quantity AS BIGINT) AND price > 0 AND fee >= 0) OR (kind = 'execution_correction' AND execution_id IS NOT NULL AND execution_revision > 1 AND supersedes_event_id IS NOT NULL AND quantity >= 0 AND quantity = CAST(quantity AS BIGINT) AND price > 0 AND fee >= 0)",
            name=op.f("ck_phase2_order_events_execution_shape"),
        ),
        sa.CheckConstraint(
            "kind <> 'rejected' OR reason IS NOT NULL",
            name=op.f("ck_phase2_order_events_rejection_reason"),
        ),
        sa.CheckConstraint(
            "kind IN ('accepted', 'rejected', 'canceled', 'execution', 'execution_correction')",
            name=op.f("ck_phase2_order_events_valid_kind"),
        ),
        sa.CheckConstraint(
            "broker_sequence > 0", name=op.f("ck_phase2_order_events_positive_broker_sequence")
        ),
        sa.CheckConstraint(
            "length(canonical_payload) BETWEEN 2 AND 262144",
            name=op.f("ck_phase2_order_events_payload_size"),
        ),
        sa.CheckConstraint(
            "length(semantic_sha256) = 64", name=op.f("ck_phase2_order_events_semantic_hash_length")
        ),
        sa.CheckConstraint(
            "received_at >= occurred_at", name=op.f("ck_phase2_order_events_valid_time_order")
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["phase2_logical_orders.order_id"],
            name=op.f("fk_phase2_order_events_order_id_phase2_logical_orders"),
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_event_id"], ["phase2_order_events.event_id"], name="superseded_event"
        ),
        sa.PrimaryKeyConstraint("event_id", name=op.f("pk_phase2_order_events")),
        sa.UniqueConstraint("order_id", "broker_sequence", name="order_broker_sequence"),
        sa.UniqueConstraint(
            "order_id", "execution_id", "execution_revision", name="execution_revision"
        ),
        sa.UniqueConstraint("semantic_sha256", name=op.f("uq_phase2_order_events_semantic_sha256")),
    )
    op.create_index(
        "ix_phase2_order_events_broker_order",
        "phase2_order_events",
        ["broker_order_id"],
        unique=False,
    )
    op.create_index(
        "ix_phase2_order_events_order_received",
        "phase2_order_events",
        ["order_id", "received_at"],
        unique=False,
    )
    op.create_table(
        "phase2_submission_attempts",
        sa.Column("attempt_id", sa.String(length=64), nullable=False),
        sa.Column("order_id", sa.String(length=64), nullable=False),
        sa.Column("account_id", sa.String(length=64), nullable=False),
        sa.Column("fencing_generation", sa.BigInteger(), nullable=False),
        sa.Column("lease_sha256", sa.String(length=64), nullable=False),
        sa.Column("fence_sha256", sa.String(length=64), nullable=False),
        sa.Column("parent_decision_id", sa.String(length=64), nullable=False),
        sa.Column("authorization_id", sa.String(length=64), nullable=False),
        sa.Column("reservation_id", sa.String(length=64), nullable=False),
        sa.Column("intent_id", sa.String(length=64), nullable=False),
        sa.Column("intent_payload_sha256", sa.String(length=64), nullable=False),
        sa.Column("risk_decision_sha256", sa.String(length=64), nullable=False),
        sa.Column("authorization_sha256", sa.String(length=64), nullable=False),
        sa.Column("fence_receipt_sha256", sa.String(length=64), nullable=False),
        sa.Column("fence_validated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("fence_valid_until", sa.DateTime(timezone=True), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("client_order_id", sa.String(length=64), nullable=False),
        sa.Column("adapter_id", sa.String(length=128), nullable=False),
        sa.Column("adapter_version", sa.String(length=64), nullable=False),
        sa.Column("operation", sa.String(length=64), nullable=False),
        sa.Column("request_sha256", sa.String(length=64), nullable=False),
        sa.Column("request_payload", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("canonical_payload", sa.Text(), nullable=False),
        sa.Column("semantic_sha256", sa.String(length=64), nullable=False),
        sa.CheckConstraint(
            "attempt_number > 0", name=op.f("ck_phase2_submission_attempts_positive_attempt_number")
        ),
        sa.CheckConstraint(
            "fencing_generation > 0", name=op.f("ck_phase2_submission_attempts_positive_generation")
        ),
        sa.CheckConstraint(
            "length(lease_sha256) = 64 AND length(fence_sha256) = 64 AND length(intent_payload_sha256) = 64 AND length(risk_decision_sha256) = 64 AND length(authorization_sha256) = 64 AND length(fence_receipt_sha256) = 64 AND length(request_sha256) = 64 AND length(semantic_sha256) = 64",
            name=op.f("ck_phase2_submission_attempts_hash_lengths"),
        ),
        sa.CheckConstraint(
            "fence_validated_at <= created_at AND created_at < fence_valid_until",
            name=op.f("ck_phase2_submission_attempts_current_fence_receipt"),
        ),
        sa.CheckConstraint(
            "length(request_payload) BETWEEN 2 AND 262144 AND length(canonical_payload) BETWEEN 2 AND 524288",
            name=op.f("ck_phase2_submission_attempts_payload_sizes"),
        ),
        sa.ForeignKeyConstraint(
            ["account_id", "fencing_generation", "lease_sha256"],
            [
                "phase2_account_leases.account_id",
                "phase2_account_leases.fencing_generation",
                "phase2_account_leases.lease_sha256",
            ],
            name="attempt_lease",
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["phase2_logical_orders.order_id"],
            name=op.f("fk_phase2_submission_attempts_order_id_phase2_logical_orders"),
        ),
        sa.ForeignKeyConstraint(
            ["parent_decision_id"],
            ["phase2_batch_decisions.decision_id"],
            name=op.f("fk_phase2_submission_attempts_parent_decision_id_phase2_batch_decisions"),
        ),
        sa.ForeignKeyConstraint(
            ["authorization_id"],
            ["phase2_batch_authorizations.authorization_id"],
            name=op.f("fk_phase2_submission_attempts_authorization_id_phase2_batch_authorizations"),
        ),
        sa.ForeignKeyConstraint(
            ["reservation_id", "parent_decision_id"],
            [
                "phase2_batch_reservations.reservation_id",
                "phase2_batch_reservations.parent_decision_id",
            ],
            name="attempt_parent_reservation",
        ),
        sa.PrimaryKeyConstraint("attempt_id", name=op.f("pk_phase2_submission_attempts")),
        sa.UniqueConstraint("order_id", "attempt_number", name="order_attempt_number"),
        sa.UniqueConstraint(
            "semantic_sha256", name=op.f("uq_phase2_submission_attempts_semantic_sha256")
        ),
    )
    op.create_index(
        "ix_phase2_submission_attempts_account_created",
        "phase2_submission_attempts",
        ["account_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_phase2_submission_attempts_client_order",
        "phase2_submission_attempts",
        ["client_order_id"],
        unique=False,
    )
    op.create_table(
        "phase2_reservation_release_events",
        sa.Column("release_event_id", sa.String(length=64), nullable=False),
        sa.Column("reservation_id", sa.String(length=64), nullable=False),
        sa.Column("authorization_id", sa.String(length=64), nullable=False),
        sa.Column("order_id", sa.String(length=64), nullable=True),
        sa.Column("attempt_id", sa.String(length=64), nullable=True),
        sa.Column("order_event_id", sa.String(length=128), nullable=True),
        sa.Column("reason", sa.String(length=32), nullable=False),
        sa.Column("finality_reference", sa.String(length=256), nullable=False),
        sa.Column("source_sha256", sa.String(length=64), nullable=False),
        sa.Column("released_cash", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("released_buy_exposure", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("released_sell_quantity", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("canonical_payload", sa.Text(), nullable=False),
        sa.Column("semantic_sha256", sa.String(length=64), nullable=False),
        sa.CheckConstraint(
            "reason IN ('approval_expired_unsent', 'broker_rejected', 'execution_accounted', 'reconciled_terminal', 'simulation_horizon_final')",
            name=op.f("ck_phase2_reservation_release_events_valid_reason"),
        ),
        sa.CheckConstraint(
            "length(canonical_payload) BETWEEN 2 AND 262144",
            name=op.f("ck_phase2_reservation_release_events_payload_size"),
        ),
        sa.CheckConstraint(
            "length(source_sha256) = 64 AND length(semantic_sha256) = 64",
            name=op.f("ck_phase2_reservation_release_events_hash_lengths"),
        ),
        sa.CheckConstraint(
            "recorded_at >= occurred_at",
            name=op.f("ck_phase2_reservation_release_events_valid_time_order"),
        ),
        sa.CheckConstraint(
            "released_cash >= 0 AND released_buy_exposure >= 0 AND released_sell_quantity >= 0 AND (released_cash > 0 OR released_buy_exposure > 0 OR released_sell_quantity > 0)",
            name=op.f("ck_phase2_reservation_release_events_positive_release"),
        ),
        sa.CheckConstraint(
            "released_sell_quantity = CAST(released_sell_quantity AS BIGINT)",
            name=op.f("ck_phase2_reservation_release_events_whole_sell_quantity"),
        ),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["phase2_submission_attempts.attempt_id"],
            name=op.f("fk_phase2_reservation_release_events_attempt_id_phase2_submission_attempts"),
        ),
        sa.ForeignKeyConstraint(
            ["authorization_id"],
            ["phase2_batch_authorizations.authorization_id"],
            name=op.f(
                "fk_phase2_reservation_release_events_authorization_id_phase2_batch_authorizations"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["order_event_id"],
            ["phase2_order_events.event_id"],
            name=op.f("fk_phase2_reservation_release_events_order_event_id_phase2_order_events"),
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["phase2_logical_orders.order_id"],
            name=op.f("fk_phase2_reservation_release_events_order_id_phase2_logical_orders"),
        ),
        sa.ForeignKeyConstraint(
            ["reservation_id"],
            ["phase2_batch_reservations.reservation_id"],
            name=op.f(
                "fk_phase2_reservation_release_events_reservation_id_phase2_batch_reservations"
            ),
        ),
        sa.PrimaryKeyConstraint(
            "release_event_id", name=op.f("pk_phase2_reservation_release_events")
        ),
        sa.UniqueConstraint(
            "semantic_sha256", name=op.f("uq_phase2_reservation_release_events_semantic_sha256")
        ),
    )
    op.create_index(
        "ix_phase2_reservation_releases_reservation_recorded",
        "phase2_reservation_release_events",
        ["reservation_id", "recorded_at"],
        unique=False,
    )
    op.create_table(
        "phase2_submission_attempt_events",
        sa.Column("event_id", sa.String(length=64), nullable=False),
        sa.Column("attempt_id", sa.String(length=64), nullable=False),
        sa.Column("sequence_number", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("previous_event_sha256", sa.String(length=64), nullable=True),
        sa.Column("dispatch_account_id", sa.String(length=64), nullable=True),
        sa.Column("dispatch_fencing_generation", sa.BigInteger(), nullable=True),
        sa.Column("dispatch_lease_sha256", sa.String(length=64), nullable=True),
        sa.Column("dispatch_fence_sha256", sa.String(length=64), nullable=True),
        sa.Column("dispatch_fence_receipt_sha256", sa.String(length=64), nullable=True),
        sa.Column(
            "dispatch_fence_validated_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "dispatch_fence_valid_until",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column("response_sha256", sa.String(length=64), nullable=True),
        sa.Column("broker_order_id", sa.String(length=128), nullable=True),
        sa.Column("error_class", sa.String(length=128), nullable=True),
        sa.Column("resolution", sa.String(length=24), nullable=True),
        sa.Column("reconciliation_sha256", sa.String(length=64), nullable=True),
        sa.Column("canonical_payload", sa.Text(), nullable=False),
        sa.Column("semantic_sha256", sa.String(length=64), nullable=False),
        sa.CheckConstraint(
            "(state = 'pending' AND sequence_number = 1 AND previous_event_sha256 IS NULL) OR (state <> 'pending' AND sequence_number > 1 AND previous_event_sha256 IS NOT NULL)",
            name=op.f("ck_phase2_submission_attempt_events_pending_is_first"),
        ),
        sa.CheckConstraint(
            "(state = 'in_flight' AND dispatch_account_id IS NOT NULL AND dispatch_fencing_generation IS NOT NULL AND dispatch_lease_sha256 IS NOT NULL AND dispatch_fence_sha256 IS NOT NULL AND dispatch_fence_receipt_sha256 IS NOT NULL AND dispatch_fence_validated_at IS NOT NULL AND dispatch_fence_valid_until IS NOT NULL) OR (state <> 'in_flight' AND dispatch_account_id IS NULL AND dispatch_fencing_generation IS NULL AND dispatch_lease_sha256 IS NULL AND dispatch_fence_sha256 IS NULL AND dispatch_fence_receipt_sha256 IS NULL AND dispatch_fence_validated_at IS NULL AND dispatch_fence_valid_until IS NULL)",
            name=op.f("ck_phase2_submission_attempt_events_dispatch_receipt_shape"),
        ),
        sa.CheckConstraint(
            "state <> 'in_flight' OR (dispatch_fencing_generation > 0 AND dispatch_fence_validated_at = occurred_at AND occurred_at < dispatch_fence_valid_until)",
            name=op.f("ck_phase2_submission_attempt_events_current_dispatch_receipt"),
        ),
        sa.CheckConstraint(
            "(state IN ('pending', 'in_flight') AND response_sha256 IS NULL AND broker_order_id IS NULL AND error_class IS NULL AND resolution IS NULL AND reconciliation_sha256 IS NULL) OR (state = 'abandoned' AND response_sha256 IS NULL AND broker_order_id IS NULL AND error_class IS NOT NULL AND resolution IS NULL AND reconciliation_sha256 IS NULL) OR (state = 'confirmed' AND response_sha256 IS NOT NULL AND broker_order_id IS NOT NULL AND error_class IS NULL AND resolution IS NULL AND reconciliation_sha256 IS NULL) OR (state = 'unknown' AND response_sha256 IS NULL AND broker_order_id IS NULL AND error_class IS NOT NULL AND resolution IS NULL AND reconciliation_sha256 IS NULL) OR (state = 'resolved' AND error_class IS NULL AND resolution IS NOT NULL AND reconciliation_sha256 IS NOT NULL AND ((resolution = 'not_submitted' AND response_sha256 IS NULL AND broker_order_id IS NULL) OR (resolution = 'broker_accepted' AND response_sha256 IS NOT NULL AND broker_order_id IS NOT NULL) OR (resolution = 'broker_rejected' AND response_sha256 IS NOT NULL)))",
            name=op.f("ck_phase2_submission_attempt_events_state_evidence_shape"),
        ),
        sa.CheckConstraint(
            "state IN ('pending', 'in_flight', 'abandoned', 'confirmed', 'unknown', 'resolved')",
            name=op.f("ck_phase2_submission_attempt_events_valid_state"),
        ),
        sa.CheckConstraint(
            "length(canonical_payload) BETWEEN 2 AND 262144",
            name=op.f("ck_phase2_submission_attempt_events_payload_size"),
        ),
        sa.CheckConstraint(
            "length(semantic_sha256) = 64",
            name=op.f("ck_phase2_submission_attempt_events_semantic_hash_length"),
        ),
        sa.CheckConstraint(
            "recorded_at >= occurred_at",
            name=op.f("ck_phase2_submission_attempt_events_valid_time_order"),
        ),
        sa.CheckConstraint(
            "(previous_event_sha256 IS NULL OR length(previous_event_sha256) = 64) AND (dispatch_lease_sha256 IS NULL OR length(dispatch_lease_sha256) = 64) AND (dispatch_fence_sha256 IS NULL OR length(dispatch_fence_sha256) = 64) AND (dispatch_fence_receipt_sha256 IS NULL OR length(dispatch_fence_receipt_sha256) = 64) AND (response_sha256 IS NULL OR length(response_sha256) = 64) AND (reconciliation_sha256 IS NULL OR length(reconciliation_sha256) = 64)",
            name=op.f("ck_phase2_submission_attempt_events_optional_hash_lengths"),
        ),
        sa.CheckConstraint(
            "resolution IS NULL OR resolution IN ('not_submitted', 'broker_accepted', 'broker_rejected')",
            name=op.f("ck_phase2_submission_attempt_events_valid_resolution"),
        ),
        sa.CheckConstraint(
            "sequence_number > 0",
            name=op.f("ck_phase2_submission_attempt_events_positive_sequence"),
        ),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["phase2_submission_attempts.attempt_id"],
            name=op.f("fk_phase2_submission_attempt_events_attempt_id_phase2_submission_attempts"),
        ),
        sa.ForeignKeyConstraint(
            [
                "dispatch_account_id",
                "dispatch_fencing_generation",
                "dispatch_lease_sha256",
            ],
            [
                "phase2_account_leases.account_id",
                "phase2_account_leases.fencing_generation",
                "phase2_account_leases.lease_sha256",
            ],
            name="dispatch_lease",
        ),
        sa.PrimaryKeyConstraint("event_id", name=op.f("pk_phase2_submission_attempt_events")),
        sa.UniqueConstraint("attempt_id", "sequence_number", name="attempt_sequence"),
        sa.UniqueConstraint(
            "semantic_sha256", name=op.f("uq_phase2_submission_attempt_events_semantic_sha256")
        ),
    )
    op.create_index(
        "ix_phase2_submission_attempt_events_state_recorded",
        "phase2_submission_attempt_events",
        ["state", "recorded_at"],
        unique=False,
    )
    op.create_table(
        "phase2_simulation_horizon_facts",
        sa.Column("horizon_id", sa.String(length=64), nullable=False),
        sa.Column("horizon_reference", sa.String(length=64), nullable=False),
        sa.Column("horizon_source_sha256", sa.String(length=64), nullable=False),
        sa.Column("reservation_id", sa.String(length=64), nullable=False),
        sa.Column("parent_decision_id", sa.String(length=64), nullable=False),
        sa.Column("authorization_id", sa.String(length=64), nullable=False),
        sa.Column("attempt_id", sa.String(length=64), nullable=False),
        sa.Column("order_id", sa.String(length=64), nullable=False),
        sa.Column("final_order_event_id", sa.String(length=128), nullable=False),
        sa.Column("replay_run_id", sa.String(length=64), nullable=False),
        sa.Column("replay_manifest_sha256", sa.String(length=64), nullable=False),
        sa.Column("replay_event_count", sa.Integer(), nullable=False),
        sa.Column("replay_watermark_count", sa.Integer(), nullable=False),
        sa.Column("simulation_result_id", sa.String(length=64), nullable=False),
        sa.Column("horizon_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("canonical_payload", sa.Text(), nullable=False),
        sa.Column("semantic_sha256", sa.String(length=64), nullable=False),
        sa.CheckConstraint(
            "replay_run_id = replay_manifest_sha256",
            name=op.f("ck_phase2_simulation_horizon_facts_content_addressed_replay"),
        ),
        sa.CheckConstraint(
            "length(horizon_id) = 36 AND length(horizon_reference) = 36 AND length(simulation_result_id) = 36 AND length(horizon_source_sha256) = 64 AND length(replay_run_id) = 64 AND length(replay_manifest_sha256) = 64 AND length(semantic_sha256) = 64",
            name=op.f("ck_phase2_simulation_horizon_facts_hash_lengths"),
        ),
        sa.CheckConstraint(
            "length(canonical_payload) BETWEEN 2 AND 524288",
            name=op.f("ck_phase2_simulation_horizon_facts_payload_size"),
        ),
        sa.CheckConstraint(
            "recorded_at >= horizon_at",
            name=op.f("ck_phase2_simulation_horizon_facts_valid_time_order"),
        ),
        sa.CheckConstraint(
            "replay_event_count >= 0 AND replay_watermark_count > 0",
            name=op.f("ck_phase2_simulation_horizon_facts_valid_replay_counts"),
        ),
        sa.ForeignKeyConstraint(
            ["authorization_id"],
            ["phase2_batch_authorizations.authorization_id"],
            name=op.f(
                "fk_phase2_simulation_horizon_facts_authorization_id_phase2_batch_authorizations"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["phase2_submission_attempts.attempt_id"],
            name=op.f("fk_phase2_simulation_horizon_facts_attempt_id_phase2_submission_attempts"),
        ),
        sa.ForeignKeyConstraint(
            ["final_order_event_id"],
            ["phase2_order_events.event_id"],
            name=op.f(
                "fk_phase2_simulation_horizon_facts_final_order_event_id_phase2_order_events"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["phase2_logical_orders.order_id"],
            name=op.f("fk_phase2_simulation_horizon_facts_order_id_phase2_logical_orders"),
        ),
        sa.ForeignKeyConstraint(
            ["parent_decision_id"],
            ["phase2_batch_decisions.decision_id"],
            name=op.f(
                "fk_phase2_simulation_horizon_facts_parent_decision_id_phase2_batch_decisions"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["replay_manifest_sha256"],
            ["replay_run_manifests.manifest_sha256"],
            name=op.f(
                "fk_phase2_simulation_horizon_facts_replay_manifest_sha256_replay_run_manifests"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["replay_run_id"],
            ["replay_run_manifests.run_id"],
            name=op.f("fk_phase2_simulation_horizon_facts_replay_run_id_replay_run_manifests"),
        ),
        sa.ForeignKeyConstraint(
            ["reservation_id"],
            ["phase2_batch_reservations.reservation_id"],
            name=op.f(
                "fk_phase2_simulation_horizon_facts_reservation_id_phase2_batch_reservations"
            ),
        ),
        sa.PrimaryKeyConstraint("horizon_id", name=op.f("pk_phase2_simulation_horizon_facts")),
        sa.UniqueConstraint(
            "horizon_reference",
            name=op.f("uq_phase2_simulation_horizon_facts_horizon_reference"),
        ),
        sa.UniqueConstraint(
            "horizon_source_sha256",
            name=op.f("uq_phase2_simulation_horizon_facts_horizon_source_sha256"),
        ),
        sa.UniqueConstraint(
            "semantic_sha256",
            name=op.f("uq_phase2_simulation_horizon_facts_semantic_sha256"),
        ),
        sa.UniqueConstraint(
            "simulation_result_id",
            name=op.f("uq_phase2_simulation_horizon_facts_simulation_result_id"),
        ),
    )
    op.create_index(
        "ix_phase2_simulation_horizon_facts_reservation_recorded",
        "phase2_simulation_horizon_facts",
        ["reservation_id", "recorded_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_phase2_simulation_horizon_facts_reservation_recorded",
        table_name="phase2_simulation_horizon_facts",
    )
    op.drop_table("phase2_simulation_horizon_facts")
    op.drop_index(
        "ix_phase2_submission_attempt_events_state_recorded",
        table_name="phase2_submission_attempt_events",
    )
    op.drop_table("phase2_submission_attempt_events")
    op.drop_index(
        "ix_phase2_reservation_releases_reservation_recorded",
        table_name="phase2_reservation_release_events",
    )
    op.drop_table("phase2_reservation_release_events")
    op.drop_index(
        "ix_phase2_submission_attempts_client_order", table_name="phase2_submission_attempts"
    )
    op.drop_index(
        "ix_phase2_submission_attempts_account_created", table_name="phase2_submission_attempts"
    )
    op.drop_table("phase2_submission_attempts")
    op.drop_index("ix_phase2_order_events_order_received", table_name="phase2_order_events")
    op.drop_index("ix_phase2_order_events_broker_order", table_name="phase2_order_events")
    op.drop_table("phase2_order_events")
    op.drop_index(
        "ix_phase2_authorization_consumptions_account_time",
        table_name="phase2_authorization_consumptions",
    )
    op.drop_table("phase2_authorization_consumptions")
    op.drop_index("ix_phase2_logical_orders_account_submitted", table_name="phase2_logical_orders")
    op.drop_table("phase2_logical_orders")
    op.drop_index(
        "ix_phase2_batch_authorizations_expires_at", table_name="phase2_batch_authorizations"
    )
    op.drop_index(
        "ix_phase2_batch_authorizations_account_instrument",
        table_name="phase2_batch_authorizations",
    )
    op.drop_table("phase2_batch_authorizations")
    op.drop_index("ix_phase2_batch_reservations_expires_at", table_name="phase2_batch_reservations")
    op.drop_index(
        "ix_phase2_batch_reservations_account_state", table_name="phase2_batch_reservations"
    )
    op.drop_table("phase2_batch_reservations")
    op.drop_index("ix_phase2_ledger_postings_entry_id", table_name="phase2_ledger_postings")
    op.drop_table("phase2_ledger_postings")
    op.drop_index("ix_phase2_batch_members_batch_ordinal", table_name="phase2_batch_members")
    op.drop_table("phase2_batch_members")
    op.drop_index(
        "ix_phase2_batch_decisions_account_evaluated", table_name="phase2_batch_decisions"
    )
    op.drop_table("phase2_batch_decisions")
    op.drop_index(
        "ix_phase2_account_lease_releases_account_generation",
        table_name="phase2_account_lease_releases",
    )
    op.drop_table("phase2_account_lease_releases")
    op.drop_table("phase2_account_lease_heads")
    op.drop_index("ix_phase2_ledger_entries_account_effective", table_name="phase2_ledger_entries")
    op.drop_table("phase2_ledger_entries")
    op.drop_index("ix_phase2_account_leases_account_generation", table_name="phase2_account_leases")
    op.drop_table("phase2_account_leases")
    # ### end Alembic commands ###
