"""Offline catalog fixtures; owner-export classification uses invented test bytes."""

from __future__ import annotations

import hashlib
import json
import stat
from dataclasses import replace
from decimal import Decimal

import pytest

from packages.adapters.research_artifacts_v2 import LocalResearchArtifactStore
from packages.application.personal_codec import decode_record, encode_record
from packages.application.personal_inputs import canonical_events, research_engine_inputs
from packages.application.research_catalog import (
    ResearchCatalogError,
    StoredResearchInputResolver,
    create_catalog_entry,
    prepare_catalog_run_inputs,
    resolve_catalog_inputs,
)
from packages.application.research_dataset import research_dataset_to_json_bytes
from packages.domain.accounting_contracts import AccountingState, SettlementCalendar
from packages.domain.daily_reference import ReferenceConfiguration
from packages.domain.engine_contracts import DailyPrice, EvaluationSpec, ScheduleSignal
from packages.domain.personal_contracts import content_digest
from packages.domain.personal_evaluation import COST_SCENARIOS
from packages.domain.report_contracts import ReportConventions
from packages.domain.research_catalog import ResearchCatalogEntry
from packages.domain.research_dataset import ResearchDataClass
from packages.domain.research_job_contracts import MAX_INPUT_BYTES, ObjectRef, ResearchRunRequest
from tests.integration.test_personal_evaluation_engine import run
from tests.unit.test_causal_engine import event
from tests.unit.test_personal_evaluation import protocol_for, source_inputs
from tests.unit.test_personal_research_dataset import _inputs, _load

D = Decimal


class MemoryObjects:
    def __init__(self):
        self.payloads = {}
        self.reads = []

    def put(self, payload, *, codec_version="personal-record/1", max_bytes=MAX_INPUT_BYTES):
        assert len(payload) <= max_bytes
        digest = hashlib.sha256(payload).hexdigest()
        self.payloads[digest] = payload
        return ObjectRef(digest, len(payload), codec_version)

    def read(self, reference, *, max_bytes=MAX_INPUT_BYTES):
        self.reads.append((reference, max_bytes))
        return self.payloads[reference.object_sha256]


def catalog(source, objects, *, archive=None):
    return create_catalog_entry(
        display_name="transparent catalog test",
        source=source,
        prior_access=protocol_for(source).prior_access,
        source_inputs=objects.put(encode_record(source)),
        archive=archive,
        settlement_calendar=objects.put(
            encode_record(source.spec.execution_policy.settlement_calendar)
        ),
    )


def ordinary(entry, source, *, cost=COST_SCENARIOS[0]):
    days = tuple(s.session_label for s in source.spec.calendar.sessions)
    return prepare_catalog_run_inputs(
        entry=entry,
        source=source,
        configuration=ReferenceConfiguration("buy_hold", 2),
        evaluation=EvaluationSpec(
            "ordinary", days[:2], days[2:6], f"retrospective-{entry.prior_access.status}"
        ),
        initial_cash=D(10000),
        cost=cost,
        current_build_pins=source.spec.pins,
    )


def request_for(prepared, entry, objects):
    return ResearchRunRequest(
        prepared.spec,
        ReportConventions(),
        objects.put(encode_record(prepared)),
        "test-owner",
        "test-request-1",
        "ordinary-run",
        entry.archive,
        entry.settlement_calendar,
    )


def real_class_fixture(tmp_path):
    # Entirely generated bytes. The owner_export enum tests retained-archive
    # classification and consistency, never empirical market accuracy.
    paths, declaration, calendar = _inputs(tmp_path)
    for item in declaration["instruments"]:
        path = paths[item["symbol"]]
        rows = json.loads(path.read_bytes())
        for row in rows:
            row["divCash"] = 0
        path.write_text(json.dumps(rows))
        item["source_sha256"] = hashlib.sha256(path.read_bytes()).hexdigest()
    declaration["source_kind"] = "owner_export"
    dataset = _load(paths, declaration, calendar)
    days = tuple(s.session_label for s in dataset.manifest.calendar.sessions)
    source = research_engine_inputs(
        dataset,
        configuration=ReferenceConfiguration("buy_hold", 2),
        evaluation=EvaluationSpec("fixture", days[:1], days[1:4], "retrospective-known_accessed"),
        settlement_calendar=SettlementCalendar("synthetic-settlement-fixture", "1", days),
        pins=source_inputs().spec.pins,
    )
    return dataset, source


def test_catalog_roundtrip_and_actual_fresh_ordinary_run_use_retained_objects(tmp_path):
    source = source_inputs()
    objects = LocalResearchArtifactStore(tmp_path / "private-objects")
    entry = catalog(source, objects)
    assert decode_record(encode_record(entry), ResearchCatalogEntry) == entry
    assert entry.dataset_id == source.spec.dataset_id and entry.catalog_id != entry.dataset_id
    assert resolve_catalog_inputs(entry, artifacts=objects) == source
    prepared = ordinary(entry, source, cost=COST_SCENARIOS[-1])
    request = request_for(prepared, entry, objects)
    assert StoredResearchInputResolver(objects).resolve(request) == prepared
    result = run(prepared)
    assert result.status == "completed" and result.final_snapshot.nav == D("9994.72")
    assert prepared.initial_state == AccountingState(source.spec.account_id)
    assert prepared.spec.risk_policy.policy_scope == "product"
    assert prepared.spec.risk_policy.fee_per_share == D(".02")
    assert prepared.spec.execution_policy.slippage_bps == D(20)
    assert (
        prepared.spec.max_cpu_cores,
        prepared.spec.max_output_bytes,
        prepared.spec.max_memory_bytes,
        prepared.spec.max_wall_seconds,
    ) == (1, 64 * 1024**2, 4 * 1024**3, 1800)
    assert all(e in source.events for e in prepared.events)
    assert all(
        stat.S_IMODE(path.stat().st_mode) == 0o600
        for path in (tmp_path / "private-objects").iterdir()
    )


def test_rebuild_pins_configuration_costs_and_access_are_explicit():
    source = source_inputs()
    objects = MemoryObjects()
    entry = catalog(source, objects)
    days = tuple(s.session_label for s in source.spec.calendar.sessions)
    pins = tuple(replace(pin, sha256="c" * 64) for pin in source.spec.pins)
    configuration = ReferenceConfiguration("trend_sma", 3)
    prepared = prepare_catalog_run_inputs(
        entry=entry,
        source=source,
        configuration=configuration,
        evaluation=EvaluationSpec("fresh", days[:2], days[2:6], "retrospective-known_accessed"),
        initial_cash=D(20000),
        cost=COST_SCENARIOS[2],
        current_build_pins=pins,
    )
    assert prepared.spec.pins == pins and prepared.spec.pins != source.spec.pins
    assert prepared.spec.strategy.sha256 == content_digest(
        (configuration, "reference-callback-adapter/1")
    )
    assert prepared.spec.initial_cash == 20000
    assert prepared.spec.dataset_sha256 == source.spec.dataset_sha256
    assert (
        prepared.spec.execution_policy.settlement_calendar
        is source.spec.execution_policy.settlement_calendar
    )
    unknown = replace(entry, prior_access=replace(entry.prior_access, status="unknown"))
    assert unknown.catalog_id != entry.catalog_id
    assert ordinary(unknown, source).spec.evaluation.prior_access_label == "retrospective-unknown"


@pytest.mark.parametrize("change", ("strategy_binding", "source_command", "instrument_scope"))
def test_catalog_cannot_admit_unbound_model_or_nonmarket_commands(change):
    source = source_inputs()
    if change == "strategy_binding":
        source = replace(
            source,
            spec=replace(source.spec, strategy=replace(source.spec.strategy, sha256="f" * 64)),
        )
    elif change == "source_command":
        at = source.spec.calendar.sessions[0].opens_at
        command = event(
            source,
            "injected-schedule",
            ScheduleSignal(
                "injected", source.spec.calendar.sessions[0].session_label, "decision_due"
            ),
            at,
            at,
        )
        events = canonical_events((*source.events, command))
        source = replace(
            source, events=events, spec=replace(source.spec, events_sha256=content_digest(events))
        )
    else:
        row = next(e for e in source.events if isinstance(e.payload, DailyPrice))
        payload = replace(row.payload, instrument_id="unregistered-SPY")
        revised = replace(
            row,
            payload=payload,
            provenance=replace(row.provenance, normalized_sha256=content_digest(payload)),
        )
        events = canonical_events(tuple(revised if e == row else e for e in source.events))
        source = replace(
            source, events=events, spec=replace(source.spec, events_sha256=content_digest(events))
        )
    with pytest.raises(ResearchCatalogError):
        catalog(source, MemoryObjects())


@pytest.mark.parametrize(
    "change", ("source_ref", "calendar_ref", "dataset", "codec", "size", "no_archive")
)
def test_catalog_identity_fields_fail_closed(change):
    source = source_inputs()
    objects = MemoryObjects()
    entry = catalog(source, objects)
    with pytest.raises(ValueError):
        if change == "source_ref":
            bad = replace(entry, source_inputs=replace(entry.source_inputs, object_sha256="a" * 64))
            ordinary(bad, source)
        elif change == "calendar_ref":
            bad = replace(
                entry,
                settlement_calendar=replace(entry.settlement_calendar, object_sha256="a" * 64),
            )
            ordinary(bad, source)
        elif change == "dataset":
            ordinary(replace(entry, dataset_sha256="b" * 64), source)
        elif change == "codec":
            replace(
                entry,
                source_inputs=replace(
                    entry.source_inputs, codec_version="personal-research-dataset-v1"
                ),
            )
        elif change == "size":
            replace(
                entry, source_inputs=replace(entry.source_inputs, byte_count=MAX_INPUT_BYTES + 1)
            )
        else:
            replace(entry, data_class=ResearchDataClass.VALIDATED_CURRENT_VINTAGE)


@pytest.mark.parametrize(
    "change",
    (
        "corrupt_bytes",
        "wrong_spec",
        "wrong_events",
        "carry",
        "outside_window",
        "wrong_settlement",
        "missing_settlement",
    ),
)
def test_run_resolver_rejects_retained_request_contradictions(change):
    source = source_inputs()
    objects = MemoryObjects()
    entry = catalog(source, objects)
    prepared = ordinary(entry, source)
    request = request_for(prepared, entry, objects)
    if change == "corrupt_bytes":
        objects.payloads[request.inputs.object_sha256] += b" "
    elif change == "wrong_spec":
        request = replace(request, spec=replace(request.spec, initial_cash=D(20000)))
    elif change == "wrong_events":
        prepared = replace(prepared, events=prepared.events[1:])
    elif change == "carry":
        state = run(prepared).final_state
        prepared = replace(
            prepared,
            initial_state=state,
            spec=replace(prepared.spec, initial_state_sha256=state.semantic_sha256),
        )
    elif change == "outside_window":
        prepared = replace(
            prepared,
            events=source.events,
            spec=replace(prepared.spec, events_sha256=source.spec.events_sha256),
        )
    elif change == "wrong_settlement":
        calendar = replace(source.spec.execution_policy.settlement_calendar, version="other")
        request = replace(request, settlement_calendar=objects.put(encode_record(calendar)))
    else:
        request = replace(request, settlement_calendar=None)
    if change in ("wrong_events", "carry", "outside_window"):
        request = replace(request, spec=prepared.spec, inputs=objects.put(encode_record(prepared)))
    with pytest.raises(ValueError):
        StoredResearchInputResolver(objects).resolve(request)


def test_real_classification_requires_exact_archive_and_independent_calendar(tmp_path):
    dataset, source = real_class_fixture(tmp_path)
    objects = MemoryObjects()
    archive = objects.put(
        research_dataset_to_json_bytes(dataset), codec_version="personal-research-dataset-v1"
    )
    # The short archive cannot use the 18-session protocol helper.
    entry = create_catalog_entry(
        display_name="generated owner-export classification fixture",
        prior_access=protocol_for(source_inputs()).prior_access,
        source=source,
        source_inputs=objects.put(encode_record(source)),
        archive=archive,
        settlement_calendar=objects.put(
            encode_record(source.spec.execution_policy.settlement_calendar)
        ),
    )
    assert resolve_catalog_inputs(entry, artifacts=objects) == source
    prepared = prepare_catalog_run_inputs(
        entry=entry,
        source=source,
        configuration=source.spec.strategy_configuration,
        evaluation=source.spec.evaluation,
        initial_cash=D(10000),
        cost=COST_SCENARIOS[0],
        current_build_pins=source.spec.pins,
    )
    request = request_for(prepared, entry, objects)
    assert StoredResearchInputResolver(objects).resolve(request) == prepared
    assert "no-historical-pit" in prepared.spec.limitations
    assert all(e in source.events for e in prepared.events)
    row = next(e for e in prepared.events if isinstance(e.payload, DailyPrice))
    payload = replace(row.payload, close_price=D(900))
    revised = replace(
        row,
        payload=payload,
        provenance=replace(row.provenance, normalized_sha256=content_digest(payload)),
    )
    events = canonical_events(tuple(revised if e == row else e for e in prepared.events))
    changed = replace(
        prepared, events=events, spec=replace(prepared.spec, events_sha256=content_digest(events))
    )
    # A self-consistent typed manifest cannot override the separately retained raw archive.
    bad = replace(request, spec=changed.spec, inputs=objects.put(encode_record(changed)))
    with pytest.raises(ResearchCatalogError, match="exact retained archive scope"):
        StoredResearchInputResolver(objects).resolve(bad)
    with pytest.raises(ValueError):
        replace(request, dataset_archive=None)


@pytest.mark.parametrize("change", ("gap", "horizon", "lookback", "access", "negative_cash"))
def test_ordinary_run_window_and_product_constraints_reject(change):
    source = source_inputs()
    entry = catalog(source, MemoryObjects())
    days = tuple(s.session_label for s in source.spec.calendar.sessions)
    configuration = ReferenceConfiguration("trend_sma", 3)
    evaluation = EvaluationSpec("ordinary", days[:2], days[2:6], "retrospective-known_accessed")
    cash = D(10000)
    if change == "gap":
        evaluation = replace(evaluation, scored_sessions=days[3:6])
    elif change == "horizon":
        evaluation = replace(evaluation, scored_sessions=days[2:])
    elif change == "lookback":
        configuration = replace(configuration, lookback=20)
    elif change == "access":
        evaluation = replace(evaluation, prior_access_label="untouched")
    else:
        cash = D(-1)
    with pytest.raises(ValueError):
        prepare_catalog_run_inputs(
            entry=entry,
            source=source,
            configuration=configuration,
            evaluation=evaluation,
            initial_cash=cash,
            cost=COST_SCENARIOS[0],
            current_build_pins=source.spec.pins,
        )
