/**
 * AUTO-GENERATED by scripts/generate_api_contracts.py.
 * Source: docs/api/openapi.json
 * These are compile-time wire types; they do not perform runtime validation.
 */

export interface components {
  schemas: {
    "AccountSummary": {
      "cash": string;
      "currency": string;
      "equity": string;
      "gross_exposure": string;
      "net_exposure": string;
      "realized_pnl": string;
      "unrealized_pnl": string;
    };
    "AlertCounts": {
      "critical": number;
      "warning": number;
    };
    "ApiErrorResponse": {
      "detail": string;
    };
    "BacktestEquityPointView": {
      "as_of": string;
      "cash": string;
      "cumulative_external_cash_flow": string;
      "cumulative_return": string;
      "drawdown": string;
      "equity": string;
      "gross_exposure": string;
      "market_value": string;
      "net_exposure": string;
      "period_return": string;
      "sequence": number;
    };
    "BacktestJobEventView": {
      "actor_id": string;
      "attempt_number": number;
      "occurred_at": string;
      "sequence": number;
      "status": components["schemas"]["BacktestJobStatus"];
      "terminal_reason_code": (string) | (null);
    };
    "BacktestJobListResponse": {
      "as_of": string;
      "jobs": Array<components["schemas"]["BacktestJobView"]>;
    };
    "BacktestJobStatus": "queued" | "running" | "completed" | "failed" | "canceled";
    "BacktestJobView": {
      "attempt_number": number;
      "claim_expires_at": (string) | (null);
      "fixture_id": string;
      "fixture_version": string;
      "history": Array<components["schemas"]["BacktestJobEventView"]>;
      "input_sha256": components["schemas"]["Sha256Text"];
      "job_id": components["schemas"]["Sha256Text"];
      "report_artifact_sha256": (components["schemas"]["Sha256Text"]) | (null);
      "report_sha256": (components["schemas"]["Sha256Text"]) | (null);
      "requested_at": string;
      "requested_by": string;
      "run_manifest_sha256": (components["schemas"]["Sha256Text"]) | (null);
      "status": components["schemas"]["BacktestJobStatus"];
      "strategy_configuration_sha256": components["schemas"]["Sha256Text"];
      "strategy_id": string;
      "strategy_version": string;
      "terminal_reason_code": (string) | (null);
      "updated_at": string;
      "worker_id": (string) | (null);
    };
    "BacktestLaunchCapability": {
      "csrf_header": string;
      "csrf_token": (string) | (null);
      "disabled_reason": (string) | (null);
      "enabled": boolean;
      "idempotency_header": string;
      "operator_id": (string) | (null);
    };
    "BacktestLaunchRequest": {
      "benchmark_sha256": components["schemas"]["Sha256Text"];
      "cost_model_sha256": components["schemas"]["Sha256Text"];
      "dataset_manifest_id": components["schemas"]["Sha256Text"];
      "dataset_manifest_sha256": components["schemas"]["Sha256Text"];
      "fill_model_sha256": components["schemas"]["Sha256Text"];
      "fixture_id": string;
      "fixture_version": string;
      "metric_conventions_sha256": components["schemas"]["Sha256Text"];
      "replay_run_id": components["schemas"]["Sha256Text"];
      "strategy_configuration_sha256": components["schemas"]["Sha256Text"];
      "strategy_id": string;
      "strategy_version": string;
    };
    "BacktestLedgerTraceView": {
      "effective_at": string;
      "entry_id": string;
      "entry_kind": string;
      "entry_sha256": components["schemas"]["Sha256Text"];
      "recorded_at": string;
      "sequence": number;
      "source_fact_id": string;
    };
    "BacktestMetricConventionsView": {
      "absolute_tolerance": string;
      "annual_risk_free_rate": string;
      "annualization_periods": number;
      "convention_id": string;
      "convention_version": string;
      "currency": string;
      "external_cash_flow_treatment": components["schemas"]["ExternalCashFlowTreatment"];
      "relative_tolerance": string;
      "return_frequency": components["schemas"]["BacktestReturnFrequency"];
      "return_type": components["schemas"]["BacktestReturnType"];
      "risk_free_rate_version": string;
      "uncertainty_method": components["schemas"]["UncertaintyMethod"];
    };
    "BacktestMetricsView": {
      "annualized_return": (string) | (null);
      "annualized_volatility": (string) | (null);
      "average_gross_exposure": string;
      "average_net_exposure": string;
      "breakeven_trade_count": number;
      "capacity_proxy": (string) | (null);
      "dividend_income": string;
      "ending_equity": string;
      "hit_rate": (string) | (null);
      "losing_trade_count": number;
      "maximum_drawdown": string;
      "profit_factor": (string) | (null);
      "realized_pnl": string;
      "sharpe_ratio": (string) | (null);
      "sortino_ratio": (string) | (null);
      "starting_equity": string;
      "total_execution_costs": string;
      "total_return": string;
      "trade_count": number;
      "turnover": string;
      "unrealized_pnl": string;
      "winning_trade_count": number;
    };
    "BacktestPositionView": {
      "as_of": string;
      "cost_basis": string;
      "dividend_income": string;
      "execution_costs": string;
      "instrument_id": string;
      "mark_price": string;
      "market_value": string;
      "quantity": string;
      "realized_pnl": string;
      "sequence": number;
      "source_projection_sha256": components["schemas"]["Sha256Text"];
      "symbol": string;
      "unrealized_pnl": string;
    };
    "BacktestReportProvenanceView": {
      "account_projection_sha256": components["schemas"]["Sha256Text"];
      "accounting_evidence_sha256": components["schemas"]["Sha256Text"];
      "corporate_action_ledger_sha256": components["schemas"]["Sha256Text"];
      "execution_ledger_sha256": components["schemas"]["Sha256Text"];
      "settlement_ledger_sha256": components["schemas"]["Sha256Text"];
    };
    "BacktestReportView": {
      "account_id": string;
      "conventions": components["schemas"]["BacktestMetricConventionsView"];
      "currency": string;
      "equity_curve": Array<components["schemas"]["BacktestEquityPointView"]>;
      "generated_at": string;
      "ledger_trace": Array<components["schemas"]["BacktestLedgerTraceView"]>;
      "metrics": components["schemas"]["BacktestMetricsView"];
      "period_end": string;
      "period_start": string;
      "positions": Array<components["schemas"]["BacktestPositionView"]>;
      "provenance": components["schemas"]["BacktestReportProvenanceView"];
      "report_artifact_sha256": components["schemas"]["Sha256Text"];
      "report_sha256": components["schemas"]["Sha256Text"];
      "trades": Array<components["schemas"]["BacktestTradeView"]>;
    };
    "BacktestReturnFrequency": "event" | "daily";
    "BacktestReturnType": "simple" | "log";
    "BacktestTradeView": {
      "closed_at": string;
      "closing_execution_sha256": components["schemas"]["Sha256Text"];
      "cost_basis": string;
      "execution_costs": string;
      "gross_pnl": string;
      "instrument_id": string;
      "net_pnl": string;
      "opened_at": string;
      "opening_execution_sha256": components["schemas"]["Sha256Text"];
      "proceeds": string;
      "quantity": string;
      "sequence": number;
      "symbol": string;
      "trade_id": string;
    };
    "CorporateActionView": {
      "action_id": string;
      "action_revision_id": string;
      "action_type": string;
      "available_at": string;
      "detail": string;
      "effective_at": string;
      "instrument_id": string;
      "revision": number;
      "symbol": string;
    };
    "DashboardSummary": {
      "account": components["schemas"]["AccountSummary"];
      "alerts": components["schemas"]["AlertCounts"];
      "as_of": string;
      "deployment": (components["schemas"]["DeploymentSummary"]) | (null);
      "health": Array<components["schemas"]["HealthCheck"]>;
      "pending_commands": number;
      "trace": Array<components["schemas"]["TraceStepView"]>;
    };
    "DataCatalogResponse": {
      "admissions": Array<components["schemas"]["MarketDataAdmissionView"]>;
      "as_of": string;
      "corporate_actions": Array<components["schemas"]["CorporateActionView"]>;
      "entitlements": Array<components["schemas"]["EntitlementView"]>;
      "instruments": Array<components["schemas"]["InstrumentView"]>;
      "jobs": Array<components["schemas"]["IngestionJobView"]>;
      "manifests": Array<components["schemas"]["DatasetManifestView"]>;
      "source": (components["schemas"]["DataSourceView"]) | (null);
    };
    "DataQualityIssueView": {
      "code": string;
      "detail": string;
      "detected_at": string;
      "issue_id": string;
      "partition_id": (string) | (null);
      "quarantined": boolean;
      "severity": string;
      "status": string;
      "summary": string;
    };
    "DataQualityResponse": {
      "as_of": string;
      "issues": Array<components["schemas"]["DataQualityIssueView"]>;
      "quarantine": Array<components["schemas"]["QuarantineView"]>;
    };
    "DataSourceView": {
      "detail": string;
      "entitlement_status": string;
      "kind": string;
      "licensed": boolean;
      "name": string;
      "source_id": string;
    };
    "DatasetManifestView": {
      "calendar_version": string;
      "corporate_action_version": string;
      "created_at": string;
      "manifest_hash": string;
      "manifest_id": string;
      "name": string;
      "partitions": Array<components["schemas"]["DatasetPartitionView"]>;
      "price_basis": string;
      "revision_policy": string;
      "row_count": number;
      "schema_version": string;
      "universe_version": string;
    };
    "DatasetPartitionView": {
      "available_at_end": string;
      "available_at_start": string;
      "checksum": string;
      "event_time_end": string;
      "event_time_start": string;
      "layer": string;
      "object_key": string;
      "ordinal": number;
      "partition_id": string;
      "quality_status": string;
      "row_count": number;
    };
    "DecisionStatus": "approved" | "rejected";
    "DeploymentState": "draft" | "approved" | "starting" | "reconciling" | "shadow" | "running" | "paused" | "draining" | "flattening" | "halted" | "stopped";
    "DeploymentSummary": {
      "id": string;
      "mode": components["schemas"]["EnvironmentMode"];
      "name": string;
      "state": components["schemas"]["DeploymentState"];
      "strategy_name": string;
    };
    "EntitlementView": {
      "feed": string;
      "licensed": boolean;
      "scope": string;
      "source_id": string;
      "status": string;
      "verified_at": (string) | (null);
    };
    "EnvironmentIdentity": {
      "account_id": string;
      "mode": components["schemas"]["EnvironmentMode"];
      "name": string;
    };
    "EnvironmentMode": "local" | "paper" | "live";
    "ExternalCashFlowTreatment": "excluded_from_return" | "time_weighted";
    "FillView": {
      "executed_at": string;
      "fee": string;
      "fill_id": string;
      "instrument_id": string;
      "notional": string;
      "order_id": string;
      "price": string;
      "quantity": string;
      "side": components["schemas"]["Side"];
      "symbol": string;
    };
    "HTTPValidationError": {
      "detail"?: Array<components["schemas"]["ValidationError"]>;
    };
    "HealthCheck": {
      "as_of": string;
      "detail": string;
      "id": string;
      "label": string;
      "status": components["schemas"]["HealthStatus"];
    };
    "HealthResponse": {
      "service": string;
      "status": components["schemas"]["ServiceStatus"];
    };
    "HealthStatus": "healthy" | "warning" | "critical" | "unknown";
    "IngestionJobView": {
      "completed_at": (string) | (null);
      "job_id": string;
      "normalized_record_count": number;
      "published_partition_count": number;
      "quarantined_record_count": number;
      "source_id": string;
      "source_record_count": number;
      "started_at": string;
      "status": string;
    };
    "InstrumentIdentifierView": {
      "available_at": string;
      "symbol": string;
      "tradable": boolean;
      "valid_from": string;
      "valid_to": (string) | (null);
      "venue": string;
    };
    "InstrumentView": {
      "asset_class": string;
      "currency": string;
      "delisted_at": (string) | (null);
      "instrument_id": string;
      "listed_at": string;
      "mappings": Array<components["schemas"]["InstrumentIdentifierView"]>;
      "name": string;
      "status": string;
    };
    "LedgerEntryView": {
      "balanced": boolean;
      "currency": string;
      "entry_id": string;
      "event_type": string;
      "posted_at": string;
      "postings": Array<components["schemas"]["PostingView"]>;
      "reference_id": string;
      "total": string;
    };
    "MarketClock": {
      "as_of": string;
      "next_transition_at": (string) | (null);
      "status": components["schemas"]["MarketStatus"];
    };
    "MarketDataAdmissionCheckView": {
      "code": string;
      "detail": string;
      "evidence_digest": (string) | (null);
      "observed_at": string;
      "status": string;
    };
    "MarketDataAdmissionView": {
      "adapter_type": string;
      "admission_run_id": string;
      "calendar_version": string;
      "checks": Array<components["schemas"]["MarketDataAdmissionCheckView"]>;
      "corporate_action_version": string;
      "coverage_end": string;
      "coverage_start": string;
      "detail": string;
      "evidence_digest": string;
      "executed_at": string;
      "executed_by": string;
      "failed_check_count": number;
      "identifier_authority": string;
      "manifest_id": (string) | (null);
      "passed_check_count": number;
      "pending_check_count": number;
      "profile_id": string;
      "profile_name": string;
      "report_digest": string;
      "required_symbols": Array<string>;
      "review_decision": (string) | (null);
      "reviewed_at": (string) | (null);
      "reviewed_by": (string) | (null);
      "source_id": string;
      "specification_digest": string;
      "status": string;
      "universe_version": string;
    };
    "MarketEventView": {
      "available_at": string;
      "close_price": string;
      "event_id": string;
      "event_time": string;
      "instrument_id": string;
      "source": string;
      "symbol": string;
    };
    "MarketStatus": "open" | "closed" | "pre_market" | "after_hours" | "unknown";
    "OrderIntentView": {
      "created_at": string;
      "decision_event_id": string;
      "decision_event_time": string;
      "expires_at": string;
      "instrument_id": string;
      "intent_id": string;
      "notional": string;
      "quantity": string;
      "reference_price": string;
      "side": components["schemas"]["Side"];
      "symbol": string;
      "target_id": string;
    };
    "OrderStatus": "working" | "filled";
    "OrderView": {
      "activation_after_event_time": string;
      "client_order_id": string;
      "filled_quantity": string;
      "instrument_id": string;
      "intent_id": string;
      "order_id": string;
      "quantity": string;
      "risk_decision_id": string;
      "side": components["schemas"]["Side"];
      "status": components["schemas"]["OrderStatus"];
      "submitted_at": string;
      "symbol": string;
    };
    "PersistenceMode": "ephemeral" | "durable" | "unavailable";
    "PositionTargetView": {
      "instrument_id": string;
      "quantity": string;
      "symbol": string;
    };
    "PositionView": {
      "average_cost": string;
      "instrument_id": string;
      "market_price": string;
      "market_value": string;
      "quantity": string;
      "symbol": string;
    };
    "PostingView": {
      "account": string;
      "credit": string;
      "currency": string;
      "debit": string;
      "instrument_id": (string) | (null);
      "units_delta": string;
    };
    "QuarantineView": {
      "partition_id": string;
      "quarantined_at": string;
      "reason": string;
      "row_count": number;
    };
    "Readiness": {
      "as_of": string;
      "reasons": Array<string>;
      "status": components["schemas"]["ReadinessStatus"];
    };
    "ReadinessStatus": "ready" | "not_ready" | "reconciling" | "halted" | "unknown";
    "RiskDecisionView": {
      "decision_id": string;
      "evaluated_at": string;
      "expires_at": string;
      "intent_id": string;
      "intent_payload_hash": string;
      "persisted": boolean;
      "persistence_mode": components["schemas"]["PersistenceMode"];
      "policy_version": string;
      "reserved_cash": string;
      "rules": Array<components["schemas"]["RiskRuleView"]>;
      "status": components["schemas"]["DecisionStatus"];
    };
    "RiskRuleView": {
      "limit": string;
      "observed": string;
      "passed": boolean;
      "rule": string;
    };
    "ServiceStatus": "ok" | "ready" | "not_ready";
    "Sha256Text": string;
    "Side": "buy" | "sell";
    "StrategyCatalogResponse": {
      "as_of": string;
      "strategies": Array<components["schemas"]["StrategyCatalogView"]>;
    };
    "StrategyCatalogView": {
      "benchmark_sha256": components["schemas"]["Sha256Text"];
      "configuration_name": string;
      "configuration_sha256": components["schemas"]["Sha256Text"];
      "cost_model_sha256": components["schemas"]["Sha256Text"];
      "dataset_manifest_sha256": components["schemas"]["Sha256Text"];
      "display_name": string;
      "fill_model_sha256": components["schemas"]["Sha256Text"];
      "fixture_id": string;
      "fixture_version": string;
      "metric_conventions_sha256": components["schemas"]["Sha256Text"];
      "parameter_schema_payload": string;
      "parameters_payload": string;
      "replay_run_id": components["schemas"]["Sha256Text"];
      "strategy_id": string;
      "strategy_version": string;
      "strategy_version_id": components["schemas"]["Sha256Text"];
    };
    "TargetPortfolioView": {
      "as_of": string;
      "expires_at": string;
      "full_snapshot": boolean;
      "strategy_id": string;
      "strategy_version": string;
      "target_id": string;
      "targets": Array<components["schemas"]["PositionTargetView"]>;
    };
    "TraceStatus": "completed" | "pending" | "failed";
    "TraceStepView": {
      "detail": string;
      "id": string;
      "occurred_at": string;
      "stage": string;
      "status": components["schemas"]["TraceStatus"];
      "title": string;
    };
    "UiBootstrap": {
      "backtest_launch": (components["schemas"]["BacktestLaunchCapability"]) | (null);
      "capabilities": Array<string>;
      "environment": components["schemas"]["EnvironmentIdentity"];
      "feature_flags": {
        [key: string]: boolean;
      };
      "market_clock": components["schemas"]["MarketClock"];
      "readiness": components["schemas"]["Readiness"];
      "stream_cursor": (string) | (null);
      "user": components["schemas"]["UserIdentity"];
    };
    "UncertaintyMethod": "none" | "iid_standard_error";
    "UserIdentity": {
      "display_name": string;
      "id": string;
    };
    "ValidationError": {
      "ctx"?: Record<string, unknown>;
      "input"?: unknown;
      "loc": Array<(string) | (number)>;
      "msg": string;
      "type": string;
    };
    "WalkingThreadTrace": {
      "account": components["schemas"]["AccountSummary"];
      "completed_at": string;
      "decision_event": components["schemas"]["MarketEventView"];
      "fill": components["schemas"]["FillView"];
      "fill_event": components["schemas"]["MarketEventView"];
      "intent": components["schemas"]["OrderIntentView"];
      "ledger_entries": Array<components["schemas"]["LedgerEntryView"]>;
      "order": components["schemas"]["OrderView"];
      "position": components["schemas"]["PositionView"];
      "risk_decision": components["schemas"]["RiskDecisionView"];
      "run_id": string;
      "started_at": string;
      "target": components["schemas"]["TargetPortfolioView"];
      "trace": Array<components["schemas"]["TraceStepView"]>;
    };
  }
}

export interface paths {
  "/api/v1/dashboard/summary": {
    get: {
      responses: {
        "200": {
          content: {
            "application/json": components["schemas"]["DashboardSummary"];
          }
        }
      }
    }
  }
  "/api/v1/data/catalog": {
    get: {
      responses: {
        "200": {
          content: {
            "application/json": components["schemas"]["DataCatalogResponse"];
          }
        }
      }
    }
  }
  "/api/v1/data/quality": {
    get: {
      responses: {
        "200": {
          content: {
            "application/json": components["schemas"]["DataQualityResponse"];
          }
        }
      }
    }
  }
  "/api/v1/research/backtests": {
    get: {
      responses: {
        "200": {
          content: {
            "application/json": components["schemas"]["BacktestJobListResponse"];
          }
        }
        "422": {
          content: {
            "application/json": components["schemas"]["HTTPValidationError"];
          }
        }
      }
    }
    post: {
      responses: {
        "202": {
          content: {
            "application/json": components["schemas"]["BacktestJobView"];
          }
        }
        "400": {
          content: {
            "application/json": components["schemas"]["ApiErrorResponse"];
          }
        }
        "401": {
          content: {
            "application/json": components["schemas"]["ApiErrorResponse"];
          }
        }
        "403": {
          content: {
            "application/json": components["schemas"]["ApiErrorResponse"];
          }
        }
        "409": {
          content: {
            "application/json": components["schemas"]["ApiErrorResponse"];
          }
        }
        "422": {
          content: {
            "application/json": components["schemas"]["HTTPValidationError"];
          }
        }
        "503": {
          content: {
            "application/json": components["schemas"]["ApiErrorResponse"];
          }
        }
      }
    }
  }
  "/api/v1/research/backtests/{job_id}": {
    get: {
      responses: {
        "200": {
          content: {
            "application/json": components["schemas"]["BacktestJobView"];
          }
        }
        "422": {
          content: {
            "application/json": components["schemas"]["HTTPValidationError"];
          }
        }
      }
    }
  }
  "/api/v1/research/backtests/{job_id}/report": {
    get: {
      responses: {
        "200": {
          content: {
            "application/json": components["schemas"]["BacktestReportView"];
          }
        }
        "422": {
          content: {
            "application/json": components["schemas"]["HTTPValidationError"];
          }
        }
      }
    }
  }
  "/api/v1/research/strategies": {
    get: {
      responses: {
        "200": {
          content: {
            "application/json": components["schemas"]["StrategyCatalogResponse"];
          }
        }
      }
    }
  }
  "/api/v1/ui/bootstrap": {
    get: {
      responses: {
        "200": {
          content: {
            "application/json": components["schemas"]["UiBootstrap"];
          }
        }
      }
    }
  }
  "/api/v1/walking-thread/trace": {
    get: {
      responses: {
        "200": {
          content: {
            "application/json": components["schemas"]["WalkingThreadTrace"];
          }
        }
      }
    }
  }
  "/health/live": {
    get: {
      responses: {
        "200": {
          content: {
            "application/json": components["schemas"]["HealthResponse"];
          }
        }
      }
    }
  }
  "/health/ready": {
    get: {
      responses: {
        "200": {
          content: {
            "application/json": components["schemas"]["HealthResponse"];
          }
        }
        "503": {
          content: {
            "application/json": components["schemas"]["HealthResponse"];
          }
        }
      }
    }
  }
}
