/**
 * AUTO-GENERATED by scripts/generate_api_contracts.py.
 * Source: docs/api/openapi.json
 * These are compile-time wire types; they do not perform runtime validation.
 */

export interface components {
  schemas: {
    "AccountSummary": {
      "cash": string;
      "currency": string;
      "equity": string;
      "gross_exposure": string;
      "net_exposure": string;
      "realized_pnl": string;
      "unrealized_pnl": string;
    };
    "AlertCounts": {
      "critical": number;
      "warning": number;
    };
    "CorporateActionView": {
      "action_id": string;
      "action_revision_id": string;
      "action_type": string;
      "available_at": string;
      "detail": string;
      "effective_at": string;
      "instrument_id": string;
      "revision": number;
      "symbol": string;
    };
    "DashboardSummary": {
      "account": components["schemas"]["AccountSummary"];
      "alerts": components["schemas"]["AlertCounts"];
      "as_of": string;
      "deployment": (components["schemas"]["DeploymentSummary"]) | (null);
      "health": Array<components["schemas"]["HealthCheck"]>;
      "pending_commands": number;
      "trace": Array<components["schemas"]["TraceStepView"]>;
    };
    "DataCatalogResponse": {
      "admissions": Array<components["schemas"]["MarketDataAdmissionView"]>;
      "as_of": string;
      "corporate_actions": Array<components["schemas"]["CorporateActionView"]>;
      "entitlements": Array<components["schemas"]["EntitlementView"]>;
      "instruments": Array<components["schemas"]["InstrumentView"]>;
      "jobs": Array<components["schemas"]["IngestionJobView"]>;
      "manifests": Array<components["schemas"]["DatasetManifestView"]>;
      "source": (components["schemas"]["DataSourceView"]) | (null);
    };
    "DataQualityIssueView": {
      "code": string;
      "detail": string;
      "detected_at": string;
      "issue_id": string;
      "partition_id": (string) | (null);
      "quarantined": boolean;
      "severity": string;
      "status": string;
      "summary": string;
    };
    "DataQualityResponse": {
      "as_of": string;
      "issues": Array<components["schemas"]["DataQualityIssueView"]>;
      "quarantine": Array<components["schemas"]["QuarantineView"]>;
    };
    "DataSourceView": {
      "detail": string;
      "entitlement_status": string;
      "kind": string;
      "licensed": boolean;
      "name": string;
      "source_id": string;
    };
    "DatasetManifestView": {
      "calendar_version": string;
      "corporate_action_version": string;
      "created_at": string;
      "manifest_hash": string;
      "manifest_id": string;
      "name": string;
      "partitions": Array<components["schemas"]["DatasetPartitionView"]>;
      "price_basis": string;
      "revision_policy": string;
      "row_count": number;
      "schema_version": string;
      "universe_version": string;
    };
    "DatasetPartitionView": {
      "available_at_end": string;
      "available_at_start": string;
      "checksum": string;
      "event_time_end": string;
      "event_time_start": string;
      "layer": string;
      "object_key": string;
      "ordinal": number;
      "partition_id": string;
      "quality_status": string;
      "row_count": number;
    };
    "DecisionStatus": "approved" | "rejected";
    "DeploymentState": "draft" | "approved" | "starting" | "reconciling" | "shadow" | "running" | "paused" | "draining" | "flattening" | "halted" | "stopped";
    "DeploymentSummary": {
      "id": string;
      "mode": components["schemas"]["EnvironmentMode"];
      "name": string;
      "state": components["schemas"]["DeploymentState"];
      "strategy_name": string;
    };
    "EntitlementView": {
      "feed": string;
      "licensed": boolean;
      "scope": string;
      "source_id": string;
      "status": string;
      "verified_at": (string) | (null);
    };
    "EnvironmentIdentity": {
      "account_id": string;
      "mode": components["schemas"]["EnvironmentMode"];
      "name": string;
    };
    "EnvironmentMode": "local" | "paper" | "live";
    "FillView": {
      "executed_at": string;
      "fee": string;
      "fill_id": string;
      "instrument_id": string;
      "notional": string;
      "order_id": string;
      "price": string;
      "quantity": string;
      "side": components["schemas"]["Side"];
      "symbol": string;
    };
    "HealthCheck": {
      "as_of": string;
      "detail": string;
      "id": string;
      "label": string;
      "status": components["schemas"]["HealthStatus"];
    };
    "HealthResponse": {
      "service": string;
      "status": components["schemas"]["ServiceStatus"];
    };
    "HealthStatus": "healthy" | "warning" | "critical" | "unknown";
    "IngestionJobView": {
      "completed_at": (string) | (null);
      "job_id": string;
      "normalized_record_count": number;
      "published_partition_count": number;
      "quarantined_record_count": number;
      "source_id": string;
      "source_record_count": number;
      "started_at": string;
      "status": string;
    };
    "InstrumentIdentifierView": {
      "available_at": string;
      "symbol": string;
      "tradable": boolean;
      "valid_from": string;
      "valid_to": (string) | (null);
      "venue": string;
    };
    "InstrumentView": {
      "asset_class": string;
      "currency": string;
      "delisted_at": (string) | (null);
      "instrument_id": string;
      "listed_at": string;
      "mappings": Array<components["schemas"]["InstrumentIdentifierView"]>;
      "name": string;
      "status": string;
    };
    "LedgerEntryView": {
      "balanced": boolean;
      "currency": string;
      "entry_id": string;
      "event_type": string;
      "posted_at": string;
      "postings": Array<components["schemas"]["PostingView"]>;
      "reference_id": string;
      "total": string;
    };
    "MarketClock": {
      "as_of": string;
      "next_transition_at": (string) | (null);
      "status": components["schemas"]["MarketStatus"];
    };
    "MarketDataAdmissionCheckView": {
      "code": string;
      "detail": string;
      "evidence_digest": (string) | (null);
      "observed_at": string;
      "status": string;
    };
    "MarketDataAdmissionView": {
      "adapter_type": string;
      "admission_run_id": string;
      "calendar_version": string;
      "checks": Array<components["schemas"]["MarketDataAdmissionCheckView"]>;
      "corporate_action_version": string;
      "coverage_end": string;
      "coverage_start": string;
      "detail": string;
      "evidence_digest": string;
      "executed_at": string;
      "executed_by": string;
      "failed_check_count": number;
      "identifier_authority": string;
      "manifest_id": (string) | (null);
      "passed_check_count": number;
      "pending_check_count": number;
      "profile_id": string;
      "profile_name": string;
      "report_digest": string;
      "required_symbols": Array<string>;
      "review_decision": (string) | (null);
      "reviewed_at": (string) | (null);
      "reviewed_by": (string) | (null);
      "source_id": string;
      "specification_digest": string;
      "status": string;
      "universe_version": string;
    };
    "MarketEventView": {
      "available_at": string;
      "close_price": string;
      "event_id": string;
      "event_time": string;
      "instrument_id": string;
      "source": string;
      "symbol": string;
    };
    "MarketStatus": "open" | "closed" | "pre_market" | "after_hours" | "unknown";
    "OrderIntentView": {
      "created_at": string;
      "decision_event_id": string;
      "decision_event_time": string;
      "expires_at": string;
      "instrument_id": string;
      "intent_id": string;
      "notional": string;
      "quantity": string;
      "reference_price": string;
      "side": components["schemas"]["Side"];
      "symbol": string;
      "target_id": string;
    };
    "OrderStatus": "working" | "filled";
    "OrderView": {
      "activation_after_event_time": string;
      "client_order_id": string;
      "filled_quantity": string;
      "instrument_id": string;
      "intent_id": string;
      "order_id": string;
      "quantity": string;
      "risk_decision_id": string;
      "side": components["schemas"]["Side"];
      "status": components["schemas"]["OrderStatus"];
      "submitted_at": string;
      "symbol": string;
    };
    "PersistenceMode": "ephemeral" | "durable" | "unavailable";
    "PositionTargetView": {
      "instrument_id": string;
      "quantity": string;
      "symbol": string;
    };
    "PositionView": {
      "average_cost": string;
      "instrument_id": string;
      "market_price": string;
      "market_value": string;
      "quantity": string;
      "symbol": string;
    };
    "PostingView": {
      "account": string;
      "credit": string;
      "currency": string;
      "debit": string;
      "instrument_id": (string) | (null);
      "units_delta": string;
    };
    "QuarantineView": {
      "partition_id": string;
      "quarantined_at": string;
      "reason": string;
      "row_count": number;
    };
    "Readiness": {
      "as_of": string;
      "reasons": Array<string>;
      "status": components["schemas"]["ReadinessStatus"];
    };
    "ReadinessStatus": "ready" | "not_ready" | "reconciling" | "halted" | "unknown";
    "RiskDecisionView": {
      "decision_id": string;
      "evaluated_at": string;
      "expires_at": string;
      "intent_id": string;
      "intent_payload_hash": string;
      "persisted": boolean;
      "persistence_mode": components["schemas"]["PersistenceMode"];
      "policy_version": string;
      "reserved_cash": string;
      "rules": Array<components["schemas"]["RiskRuleView"]>;
      "status": components["schemas"]["DecisionStatus"];
    };
    "RiskRuleView": {
      "limit": string;
      "observed": string;
      "passed": boolean;
      "rule": string;
    };
    "ServiceStatus": "ok" | "ready" | "not_ready";
    "Side": "buy" | "sell";
    "TargetPortfolioView": {
      "as_of": string;
      "expires_at": string;
      "full_snapshot": boolean;
      "strategy_id": string;
      "strategy_version": string;
      "target_id": string;
      "targets": Array<components["schemas"]["PositionTargetView"]>;
    };
    "TraceStatus": "completed" | "pending" | "failed";
    "TraceStepView": {
      "detail": string;
      "id": string;
      "occurred_at": string;
      "stage": string;
      "status": components["schemas"]["TraceStatus"];
      "title": string;
    };
    "UiBootstrap": {
      "capabilities": Array<string>;
      "environment": components["schemas"]["EnvironmentIdentity"];
      "feature_flags": {
        [key: string]: boolean;
      };
      "market_clock": components["schemas"]["MarketClock"];
      "readiness": components["schemas"]["Readiness"];
      "stream_cursor": (string) | (null);
      "user": components["schemas"]["UserIdentity"];
    };
    "UserIdentity": {
      "display_name": string;
      "id": string;
    };
    "WalkingThreadTrace": {
      "account": components["schemas"]["AccountSummary"];
      "completed_at": string;
      "decision_event": components["schemas"]["MarketEventView"];
      "fill": components["schemas"]["FillView"];
      "fill_event": components["schemas"]["MarketEventView"];
      "intent": components["schemas"]["OrderIntentView"];
      "ledger_entries": Array<components["schemas"]["LedgerEntryView"]>;
      "order": components["schemas"]["OrderView"];
      "position": components["schemas"]["PositionView"];
      "risk_decision": components["schemas"]["RiskDecisionView"];
      "run_id": string;
      "started_at": string;
      "target": components["schemas"]["TargetPortfolioView"];
      "trace": Array<components["schemas"]["TraceStepView"]>;
    };
  }
}

export interface paths {
  "/api/v1/dashboard/summary": {
    get: {
      responses: {
        "200": {
          content: {
            "application/json": components["schemas"]["DashboardSummary"];
          }
        }
      }
    }
  }
  "/api/v1/data/catalog": {
    get: {
      responses: {
        "200": {
          content: {
            "application/json": components["schemas"]["DataCatalogResponse"];
          }
        }
      }
    }
  }
  "/api/v1/data/quality": {
    get: {
      responses: {
        "200": {
          content: {
            "application/json": components["schemas"]["DataQualityResponse"];
          }
        }
      }
    }
  }
  "/api/v1/ui/bootstrap": {
    get: {
      responses: {
        "200": {
          content: {
            "application/json": components["schemas"]["UiBootstrap"];
          }
        }
      }
    }
  }
  "/api/v1/walking-thread/trace": {
    get: {
      responses: {
        "200": {
          content: {
            "application/json": components["schemas"]["WalkingThreadTrace"];
          }
        }
      }
    }
  }
  "/health/live": {
    get: {
      responses: {
        "200": {
          content: {
            "application/json": components["schemas"]["HealthResponse"];
          }
        }
      }
    }
  }
  "/health/ready": {
    get: {
      responses: {
        "200": {
          content: {
            "application/json": components["schemas"]["HealthResponse"];
          }
        }
        "503": {
          content: {
            "application/json": components["schemas"]["HealthResponse"];
          }
        }
      }
    }
  }
}
